- id: '157942923238593'
  alias: 'Gate just got open hide ;) '
  trigger:
  - entity_id: binary_sensor.garden_gate
    from: 'off'
    platform: state
    to: 'on'
  action:
  - data:
      delay: 00:00:02
      message: Someones just opened the gate!
      sonos_entity: media_player.kitchen
      volume: 0.5
    service: script.sonos_say
