sensor:
  - name: morning_alarm
    state: >
      {% set alarm_time = as_timestamp(states('sensor.next_alarm')) %}
      {% set time_now = as_timestamp(now()) %}
      {% if alarm_time != None %}
        {{ time_now >= alarm_time - 1800 }}
      {% else %}
        {{ unavailable }}
      {% endif %}
