
- platform: template
  sensors:
    morning_alarm:
      value_template: >-
        {% set alarm_time = as_timestamp(states('sensor.next_alarm')) %}
        {% set time_now = as_timestamp(now()) %}
        {% if alarm_time != None %}
          {{ time_now >= alarm_time - 1800 }}
        {% else %}
          {{ unavailable }}
        {% endif %}


- platform: template
  sensors:
    lights:
      friendly_name: "Enable auto lights"
      value_template: "{{ states('sensor.out_side_lux')|float < 1400 }}"