- platform: mqtt
  name: "Porch Movement"
  device_class: motion
  state_topic: "Blueiris/Porch"
  payload_on: "on"
  payload_off: "off"
  off_delay: 30

- platform: mqtt
  name: "Backgarden Movement"
  device_class: motion
  state_topic: "Blueiris/Backgarden"
  payload_on: "on"
  off_delay: 30

- platform: mqtt
  name: "Sidedrive Movement"
  device_class: motion
  state_topic: "Blueiris/Sidedrive"
  payload_on: "on"
  off_delay: 30


- platform: mqtt
  name: "Coop Movement"
  device_class: motion
  state_topic: "Blueiris/Coop"
  payload_on: "on"
  off_delay: 30


- platform: mqtt
  name: "Driveway Movement"
  device_class: motion
  state_topic: "Blueiris/Driveway"
  payload_on: "on"
  payload_off: "off"
  off_delay: 30



- platform: template
  sensors:
    alarm_heating_on:
      value_template: >-
        {% set alarm_time = as_timestamp(states('sensor.next_alarm')) %}
        {% set time_now = as_timestamp(now()) %}
        {% if alarm_time != None %}
          {{ time_now >= alarm_time - 1800 }}
        {% else %}
          {{ unavailable }}
        {% endif %}


- platform: template
  sensors:
    Lights?:
      friendly_name: "Enable auto lights"
      value_template: "{{ states('sensor.lux')|float > 2000 }}"