- platform: generic
  name: Porch_rtsp
  still_image_url: http://admin:Farmer79!!@192.168.110.241/cgi-bin/snapshot.cgi
  stream_source: 'rtsp://admin:Farmer79!!@192.168.110.241/cam/realmonitor?channel=1&subtype=00&authbasic=YWRtaW46RmFybWVyNzkhIQ=='
  verify_ssl: false

- platform: generic
  name: Backgarden_rtsp
  still_image_url: http://admin:Farmer79!!@192.168.110.242/cgi-bin/snapshot.cgi
  stream_source: 'rtsp://admin:Farmer79!!@192.168.110.242/cam/realmonitor?channel=1&subtype=00&authbasic=YWRtaW46RmFybWVyNzkhIQ=='
  verify_ssl: false

- platform: generic
  name: Driveway_rtsp
  still_image_url: http://admin:Farmer79!!@192.168.110.243/cgi-bin/snapshot.cgi
  stream_source: 'rtsp://admin:Farmer79!!@192.168.110.243/cam/realmonitor?channel=1&subtype=00&authbasic=YWRtaW46RmFybWVyNzkhIQ=='
  verify_ssl: false

