- platform: generic_thermostat
  name: Kitchen
  heater: switch.underfloor_heating
  target_sensor: sensor.underfloor_heating
  min_temp: 18
  max_temp: 23
  ac_mode: false
  target_temp: 20.5
  cold_tolerance: 0.3
  hot_tolerance: 0
  min_cycle_duration:
    seconds: 5
  keep_alive:
    minutes: 3
  initial_hvac_mode: "off"
  away_temp: 20.5
  precision: 0.1

- platform: generic_thermostat
  name: Upstairs
  heater: switch.upstairs_radiators
  target_sensor: sensor.upstairs_temperature
  min_temp: 18
  max_temp: 25
  ac_mode: false
  target_temp: 19
  cold_tolerance: 0.3
  hot_tolerance: 0
  min_cycle_duration:
    seconds: 5
  keep_alive:
    minutes: 3
  initial_hvac_mode: "off"
  away_temp: 18
  precision: 0.1

- platform: generic_thermostat
  name: Downstairs
  heater: switch.downstairs_radiators
  target_sensor: sensor.lounge_temperature
  min_temp: 18
  max_temp: 25
  ac_mode: false
  target_temp: 19
  cold_tolerance: 0.3
  hot_tolerance: 0
  min_cycle_duration:
    seconds: 5
  keep_alive:
    minutes: 3
  initial_hvac_mode: "off"
  away_temp: 18
  precision: 0.1

- platform: generic_thermostat
  name: Office
  heater: switch.office_heater
  target_sensor: sensor.office_temperature
  min_temp: 15
  max_temp: 23
  ac_mode: false
  target_temp: 15.0
  cold_tolerance: 0.3
  hot_tolerance: 0
  min_cycle_duration:
    seconds: 5
  keep_alive:
    minutes: 3
  initial_hvac_mode: "off"
  away_temp: 15.0
  precision: 0.1