
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
# customize: !include customize.yaml

#recorder:
#  purge_keep_days: 5
#  db_url: mysql://hassio:Farmer79@192.168.111.2/hass?charset=utf8

logger:

history: 

http:

mobile_app:

lovelace:
  mode: yaml

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include_dir_merge_list automation
script: !include scripts.yaml
scene: !include scenes.yaml
input_boolean: !include input_boolean.yaml
climate: !include climate.yaml
light: !include light.yaml
cloud: !include cloud.yaml
sensor: !include sensor.yaml
# notify: !include notify.yaml
timer: !include timer.yaml
# sonos: !include sonos.yaml
binary_sensor: !include binary_sensor.yaml
input_select: !include input_select.yaml

