
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:


influxdb:
  ssl: false
  host: 192.168.110.113
  port: 8086
  database: home_assistant
  tags:
    source: HA
  default_measurement: state

recorder:
  purge_keep_days: 7
  exclude:
    entities:
      - binary_sensor.hallway_pir
      - binary_sensor.kitchen_pir
      - binary_sensor.landing_pir
      - binary_sensor.lila_s_pir
      - binary_sensor.lounge_pir
      - binary_sensor.playroom_pir
      - binary_sensor.raf_s_pir
      - sensor.ds_pirs
      - sensor.us_pirs
      - binary_sensor.thea_s_bedroom_pir

logger:

history: 

http:

mobile_app:

lovelace:
  mode: yaml

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include_dir_merge_list automation
script: !include scripts.yaml
scene: !include scenes.yaml
input_boolean: !include input_boolean.yaml
climate: !include climate.yaml
light: !include light.yaml
cloud: !include cloud.yaml
sensor: !include sensor.yaml
notify: !include notify.yaml
binary_sensor: !include binary_sensor.yaml
input_select: !include input_select.yaml
# resources: !include lovelace/rescources/resources.yaml
# input_datetime: !include input_datetime.yaml