
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:



spotify:
  client_id: c067b910851c444397028bf135460551
  client_secret: 354b0b1d7ff749089fd67acb82ce550c


influxdb:
  ssl: false
  host: 192.168.110.113
  port: 8086
  database: home_assistant
  tags:
    source: HA
  default_measurement: state

logger:

history: 

http:

mobile_app:

lovelace:
  mode: yaml

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include_dir_merge_list automation
script: !include scripts.yaml
scene: !include scenes.yaml
input_boolean: !include input_boolean.yaml
climate: !include climate.yaml
light: !include light.yaml
cloud: !include cloud.yaml
sensor: !include sensor.yaml
notify: !include notify.yaml
binary_sensor: !include binary_sensor.yaml
input_select: !include input_select.yaml
# input_datetime: !include input_datetime.yaml
