
version: "3.9"

networks:
    Automation:

services:
  homeassistant:
    image: homeassistant/home-assistant:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /nfs/Media/Music:/media
      - /mnt/docker_data/home-assistant/Config/:/config
    ports:
      - 8123:8123
    #depends_on:
    #  - ha_influxd
    networks:
      Automation:



