
version: "3.9"

networks:
    dock_inter:
        external: true
        name: dock_inter

services:
  homeassistant:
    image: homeassistant/home-assistant:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      #- /opt/Media:/media
      /mnt/docker_data/Homeassistant:/config
    ports:
      - 8123:8123
    #depends_on:
    #  - ha_influxd
    networks:
      - dock_inter
