version: "3.9"

networks:
  IOT:
    external: true
    name: swarm-IOT
  swarm_private:
    external: true
    name: swarm_private

services:
  homeassistant:
    image: homeassistant/home-assistant:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
    # - /nfs/Media/Music:/media
      - /mnt/docker_data/home-assistant/Config/:/config
    ports:
      - 8123:8123
    
    labels:
      com.docker.swarm.reschedule-policies: on-node-failure

    #depends_on:
    #  - ha_influxd
    
    networks:
      IOT:
        aliases:
          - Hass
        
      swarm_private:
        aliases:
          - interfrigate

