- platform: template
  sensors:
    ds_pirs:
    friendly_name: "No activity downstairs"
    value_template: >-
      {{ is_state('binary_sensor.hallway_pir' , 'off')
          and is_state('binary_sensor.kitchen_pir' , 'off')
          and is_state('binary_sensor.lounge_pir' , 'off') }}

- platform: template
  sensors:
    us_pirs:
      friendly_name: "No activity upstairs"
      value_template: >-
        {{ is_state('binary_sensor.landing_pir' , 'off')
            and is_state('binary_sensor.lila_s_pir' , 'off')
            and is_state('binary_sensor.raf_s_pir' , 'off')
            and is_state('binary_sensor.thea_s_bedroom_pir' , 'off') }}

- platform: template
  sensors:
    all_pirs:
      friendly_name: All pir´s
      value_template: >-
        {{ is_state('binary_sensor.landing_pir' , 'off')
            and is_state('binary_sensor.hallway_pir' , 'off')
            and is_state('binary_sensor.lila_s_pir' , 'off')
            and is_state('binary_sensor.raf_s_pir' , 'off')
            and is_state('binary_sensor.kitchen_pir' , 'off')
            and is_state('binary_sensor.lounge_pir' , 'off')
            and is_state ('binary_sensor.playroom_pir' , 'off')
            and is_state('binary_sensor.thea_s_bedroom_pir' , 'off') }}

- platform: min_max
  entity_ids:
    - sensor.porch_temperature
    - sensor.driveway_temperature
  type: mean
  name: Outside temperature

- platform: min_max
  entity_ids:
    - sensor.landing_temperature
    - sensor.lila_room_temperature
    - sensor.master_room_temperature
    - sensor.thea_room_temperature
  type: mean
  name: Upstairs temperature

- platform: min_max
  entity_ids:
    - sensor.lounge_temperature
    - sensor.playroom_temperature
    - sensor.downstairs_toilet_temperature
    - sensor.hallway_temperature
  type: mean
  name: Downstairs temperature

- platform: time_date
  display_options:
    - 'time'
    - 'date'

- platform: template
  sensors:
      next_alarm:
        friendly_name: Morning Alarm
        value_template: "{{ [states('sensor.faye_phone_next_alarm'), states('sensor.rich_phone_next_alarm')] | min }}"
        attribute_templates:
          alarm_time: >-
            {{ as_timestamp(states('sensor.next_alarm')) | timestamp_custom('%H:%M') }}
          minutes_left: >-
            {% set dummy = states("sensor.time") %}
            {{((states('sensor.next_alarm')|as_timestamp|int - now()|as_timestamp|int)/60)|int}}
          text_time_left: >-
            {% set time = state_attr('sensor.next_alarm','minutes_left') %}
            {% set hours = ((time | int /  60) | string).split('.')[0] %}
            {% set minutes = time | int % 60 %}
            {{hours}} hours and {{minutes}} minutes
          text_whos_alarm: >-
            {% if states('sensor.rich_phone_next_alarm') == states('sensor.faye_phone_next_alarm') %} Inget alarm
            {% elif ((states('sensor.next_alarm')|as_timestamp|int - now()|as_timestamp|int)/60)|int ==  ((states('sensor.faye_phone_next_alarm')|as_timestamp|int - now()|as_timestamp|int)/60)|int %}
            Faye´s
            {% elif ((states('sensor.next_alarm')|as_timestamp|int - now()|as_timestamp|int)/60)|int ==  ((states('sensor.rich_phone_next_alarm')|as_timestamp|int - now()|as_timestamp|int)/60)|int %}
            Rich´s
            {% else %}
            ERROR
            {% endif %}

- platform: mqtt_room
  device_id: 'apple:1005:9-12'
  name: 'Rich Macbook'
  state_topic: 'espresense/devices/apple:1005:9-12'
  timeout: 60
  away_timeout: 120 # number of seconds after which the enitity will get status not_home 