apiVersion: v1
kind: Service
metadata:
  labels:
    app: homeassistant
  name: hass
  namespace: hassspace
  annotations:
    #metallb.universe.tf/loadBalancerIPs: 192.168.110.111
        #metallb.universe.tf/address-pool: cheap
spec:
  selector:
    app: hass
  ports:
  - name: port8123
    port: 8123
    protocol: TCP
    nodePort: 8123
  type: LoadBalancer
