apiVersion: v1
kind: Service
metadata:
  labels:
    app: homeassistant
  name: homeassistant
  namespace: hassspace
spec:
  selector:
    app: hass
  ports:
  - port: 8123
    nodePort: 38123
    name: port8123
    protocol: TCP
  externalTrafficPolicy: Local
  type: LoadBalancer