apiVersion: v1
kind: Service
metadata:
  labels:
    app: homeassistant
  name: hass
  namespace: hassspace
spec:
  selector:
    app: hass
  ports:
  - name: port8123
    port: 8123
    protocol: TCP
    nodePort: 30002
  externalTrafficPolicy: Local
  type: LoadBalancer