binary_sensor:
    
    - name: "No activity downstairs"
      state: >
        {{ is_state('binary_sensor.hallway_pir' , 'off')
            and is_state('binary_sensor.kitchen_pir' , 'off')
            and is_state('binary_sensor.lounge_pir' , 'off') }}

    - name: "No activity upstairs"
      state: >
        {{ is_state('binary_sensor.landing_pir' , 'off')
            and is_state('binary_sensor.lila_s_pir' , 'off')
            and is_state('binary_sensor.raf_s_pir' , 'off')
            and is_state('binary_sensor.thea_s_bedroom_pir' , 'off') }}

    - name: All pirs
      state: >
        {{ is_state('binary_sensor.landing_pir' , 'off')
            and is_state('binary_sensor.hallway_pir' , 'off')
            and is_state('binary_sensor.lila_s_pir' , 'off')
            and is_state('binary_sensor.raf_s_pir' , 'off')
            and is_state('binary_sensor.kitchen_pir' , 'off')
            and is_state('binary_sensor.lounge_pir' , 'off')
            and is_state ('binary_sensor.playroom_pir' , 'off')
            and is_state('binary_sensor.thea_s_bedroom_pir' , 'off') }}
    
    - name: Enable auto lights
      state: >
        {{ states('sensor.out_side_lux')|float < 1400 }}
    
    - name: morning_alarm
      state: >
        {% set alarm_time = as_timestamp(states('sensor.next_alarm')) %}
        {% set time_now = as_timestamp(now()) %}
        {% if alarm_time != None %}
          {{ time_now >= alarm_time - 1800 }}
        {% else %}
          {{ unavailable }}
        {% endif %}
  

sensor:
    
    