binary_sensor:
    
    - name: "No activity downstairs"
      state: >
        {{ is_state('binary_sensor.hallway_pir' , 'off')
            and is_state('binary_sensor.kitchen_pir' , 'off')
            and is_state('binary_sensor.lounge_pir' , 'off') }}

    - name: "No activity upstairs"
      state: >
        {{ is_state('binary_sensor.landing_pir' , 'off')
            and is_state('binary_sensor.lila_s_pir' , 'off')
            and is_state('binary_sensor.raf_s_pir' , 'off')
            and is_state('binary_sensor.thea_s_bedroom_pir' , 'off') }}

    - name: All pirs
      state: >
        {{ is_state('binary_sensor.landing_pir' , 'off')
            and is_state('binary_sensor.hallway_pir' , 'off')
            and is_state('binary_sensor.lila_s_pir' , 'off')
            and is_state('binary_sensor.raf_s_pir' , 'off')
            and is_state('binary_sensor.kitchen_pir' , 'off')
            and is_state('binary_sensor.lounge_pir' , 'off')
            and is_state ('binary_sensor.playroom_pir' , 'off')
            and is_state('binary_sensor.thea_s_bedroom_pir' , 'off') }}
    
    - name: Enable auto lights
      state: >
        {{ states('sensor.out_side_lux')|float < 1400 }}
    
    - name: morning_alarm
      state: >
        {% set alarm_time = as_timestamp(states('sensor.next_alarm')) %}
        {% set time_now = as_timestamp(now()) %}
        {% if alarm_time != None %}
          {{ time_now >= alarm_time - 1800 }}
        {% else %}
          {{ unavailable }}
        {% endif %}
  

sensor:
    
    - name: next alarm
      state: >
        {{ [states('sensor.faye_phone_next_alarm'), states('sensor.rich_phone_next_alarm')] | min }}
        attribute_templates:
          alarm_time: >-
            {{ as_timestamp(states('sensor.next_alarm')) | timestamp_custom('%H:%M') }}
          minutes_left: >-
            {% set dummy = states("sensor.time") %}
            {{((states('sensor.next_alarm')|as_timestamp|int - now()|as_timestamp|int)/60)|int}}
          text_time_left: >-
            {% set time = state_attr('sensor.next_alarm','minutes_left') %}
            {% set hours = ((time | int /  60) | string).split('.')[0] %}
            {% set minutes = time | int % 60 %}
            {{hours}} hours and {{minutes}} minutes
          text_whos_alarm: >-
            {% if states('sensor.rich_phone_next_alarm') == states('sensor.faye_phone_next_alarm') %} Inget alarm
            {% elif ((states('sensor.next_alarm')|as_timestamp|int - now()|as_timestamp|int)/60)|int ==  ((states('sensor.faye_phone_next_alarm')|as_timestamp|int - now()|as_timestamp|int)/60)|int %}
            Faye´s
            {% elif ((states('sensor.next_alarm')|as_timestamp|int - now()|as_timestamp|int)/60)|int ==  ((states('sensor.rich_phone_next_alarm')|as_timestamp|int - now()|as_timestamp|int)/60)|int %}
            Rich´s
            {% else %}
            ERROR
            {% endif %}

    