resources:
  - url: /local/plugins/card-modder.js?v=1
    type: js
  - url: /local/simple-thermostat.js
    type: module
  - url: /local/auto-entities.js
    type: module
  - url: /local/weather-card/weather-card.js
    type: module

title: Edenbridge
views:  
  - title: main
    path: main
    icon: mdi:information-outline
    cards:
      - type: entities
        title: Who´s at Home
        entities:
          - person.faye_dawson
          - person.richard_dawson
      
      - type: entities
        title: Sensor´s 
        entities:
          - sun.sun
          - sensor.us_pirs
          - sensor.ds_pirs
          - sensor.out_side_lux
          - input_select.house_mode
              
  - title: Heating
    icon: mdi:radiator
    path: heating
    cards:
      - type: 'custom:simple-thermostat'
        entity: climate.downstairs
        step_size: 1
        sensors:
          - entity: sensor.playroom_s_room_humidity
            name: Humidity
      - type: 'custom:simple-thermostat'
        entity: climate.upstairs
        step_size: 1
        sensors:
          - entity: sensor.playroom_s_room_humidity
            name: Humidity
      - type: 'custom:simple-thermostat'
        entity: climate.kitchen
        step_size: 1
        sensors:
          - entity: sensor.kitchen_humidity
            name: Humidity
    
          
      - type: vertical-stack  
        cards:

          - type: entities
            title: Heating Control´s 
            entities:
              - switch.downstairs_radiators
              - switch.upstairs_radiators
              - entity:  binary_sensor.cylinder_thermostats
              - switch.underfloor_heating
              - switch.hotwater
              - switch.boiler_call

  - title: Rooms
    path: rooms
    icon: mdi:home-outline

    cards:
        
      - type: glance
        title: Master bedroom 
        entities:
          - entity: light.master_bedroom_light
          - entity: light.faye_s_bedside_lamp
          - entity: light.rich_s_bedside_lamp
          - entity: light.master_bedroom_bedside_lamps
          - entity:  binary_sensor.raf_s_pir
          
      - type: glance
        title: Lila´s bedroom 
        entities:
          - entity: light.lila_s_bedroom_light
          - entity:  binary_sensor.lila_s_pir
          
      - type: glance
        title: Thea´s bedroom 
        entities:
           - entity: light.thea_s_bedroom_light
           - entity:  binary_sensor.thea_s_bedroom_pir
          
      - type: glance
        title: Playroom 
        entities:
          - entity: light.playrooms_light
          - entity: binary_sensor.playroom_pir
          - entity: light.globe_lamp
          - entity: switch.tv
                
          
      - type: glance
        title: Lounge 
        entities:
          - entity: light.lounge_bookshelf_lights
          - entity: light.lounge_lights
          - entity: binary_sensor.lounge_pir
          
      - type: glance
        title: Kitchen 
        entities:
          - entity: light.kitchen_dining_lights
          - entity: light.kitchen_side_lights
          - entity: light.kitchen_island_lights
          - entity: light.kitchen_fairy_lights
          - entity: binary_sensor.kitchen_pir
          - entity: light.boiler_lamp
      - type: glance
        title: Landing / Hallway
        entities:
          - entity: light.landing_lights
          - entity: light.hallway_lights
            
      - type: glance
        title: Garage
        entities:
          - entity: binary_sensor.garage_door
          - entity: switch.garage_door_lock
          - entity: light.garage_lights
          
      - type: glance
        title: Back garden
        entities:
          - entity: binary_sensor.garden_gate 
          - entity: light.garden_lights
          
      - type: glance
        title: Front garden
        entities:
          - entity: light.porch_light
          - entity: binary_sensor.frontgarden_gate
          - entity: binary_sensor.front_door

      - type: glance
        title: Bathroom
        entities:
          - entity: light.bathroom_mirror
          - entity: light.bathroom
          - entity: binary_sensor.bathroom_switch
          - entity: binary_sensor.bathroom_mirror_switch
          - entity: switch.bathroom_extractor_fan
          - entity: sensor.bathroom_humidity
          - entity: sensor.bathroom_temperature
      
      - type: glance
        title: Downstairs toilet 
        entities:
          - entity: switch.downstairs_toilet_extractor_fan
          - entity: sensor.downstairs_toilet_humidity
          - entity: sensor.downstairs_toilet_temperature



  
  - title: Master's Switch's
    icon: mdi:toggle-switch
    path: switchs
    cards:
     
      - type: glance
        entities:
          - entity: input_boolean.coop_cleanning
          - entity: input_boolean.guest_room
          - entity: input_boolean.eating_mode
