title: Edenbridge
views:  
  - title: main
    path: main
    icon: mdi:information-outline
    cards:

      - type: entities
        title: Who´s at Home
        entities:
          - person.faye_dawson
          - person.richard_dawson
      
