title: Edenbridge
views:  
  - title: main
    path: main
    icon: mdi:information-outline
    panel: true
    cards:
      
      - type: horizontal-stack
        cards:
          - type: entities
            title: Who´s at Home
            entities:
              - person.faye_dawson
              - person.richard_dawson
      
          - type: entities
            title: Sensor´s 
            entities:
              - sun.sun
              - sensor.us_pirs
              - sensor.ds_pirs
              - sensor.out_side_lux
              - input_select.house_mode

  - title: Heating
    icon: mdi:radiator
    path: heating
    panel: true
    cards:
      - type: horizontal-stack  
        
        cards:
          - type: 'custom:simple-thermostat'
            entity: climate.downstairs
            step_size: 1
            sensors:
              - entity: sensor.playroom_s_room_humidity
                name: Humidity
          - type: 'custom:simple-thermostat'
            entity: climate.upstairs
            step_size: 1
            sensors:
              - entity: sensor.hallway_humidity
                name: Humidity
          - type: 'custom:simple-thermostat'
            entity: climate.kitchen
            step_size: 1
            sensors:
              - entity: sensor.kitchen_humidity
                name: Humidity
    
          
          - type: horizontal-stack   
            cards:

              - type: entities
                title: Heating Control´s 
                entities:
                  - switch.downstairs_radiators
                  - switch.upstairs_radiators
                  - binary_sensor.cylinder_thermostats
                  - switch.underfloor_heating
                  - switch.hotwater
                  - switch.boiler_call

  - title: Rooms
    path: rooms
    icon: mdi:home-outline

    cards:
        
      - type: glance
        title: Master bedroom 
        entities:
          - light.master_bedroom_light
          - light.faye_s_bedside_lamp
          - light.rich_s_bedside_lamp
          - light.master_bedroom_bedside_lamps
          - binary_sensor.raf_s_pir
          
      - type: glance
        title: Lila´s bedroom 
        entities:
          - light.lila_s_bedroom_light
          - binary_sensor.lila_s_pir
          
      - type: glance
        title: Thea´s bedroom 
        entities:
           - light.thea_s_bedroom_light
           - binary_sensor.thea_s_bedroom_pir
          
      - type: glance
        title: Playroom 
        entities:
           - light.playrooms_light
           - binary_sensor.playroom_pir
           - light.globe_lamp
                
          
      - type: glance
        title: Lounge 
        entities:
          - light.lounge_bookshelf_lights
          - light.lounge_lights
          - binary_sensor.lounge_pir
          
      - type: glance
        title: Kitchen 
        entities:
          - light.kitchen_dining_lights
          - light.kitchen_side_lights
          - light.kitchen_island_lights
          - light.kitchen_fairy_lights
          - light.kitchen_lamp
          - binary_sensor.kitchen_pir
          
      - type: glance
        title: Landing / Hallway
        entities:
          - light.landing_lights
          - light.hallway_lights
            
      - type: glance
        title: Garage
        entities:
          - binary_sensor.garage_door
          - switch.garage_door_lock
          - light.garage_lights
          
      - type: glance
        title: Back garden
        entities:
          - binary_sensor.garden_gate 
          - light.garden_lights
          
      - type: glance
        title: Front garden
        entities:
          - light.porch_light
          - binary_sensor.frontgarden_gate
          - binary_sensor.front_door
  
  
  - title: Master's Switch's
    icon: mdi:toggle-switch
    path: switchs
    cards:
     
      - type: glance
        entities:
          - input_boolean.coop_cleanning
          - input_boolean.guest_room
          - input_boolean.eating_mode
