title: Edenbridge
views:  
  - title: main
    path: main
    icon: mdi:information-outline
    cards:

      - type: entities
        name: 
        entities:
          - device_tracker.paulus
          - device_tracker.anne_there
      
