title: Edenbridge
views:
  - badges:
        - sensor.time
        - sun.sun
        
  - title: main
    path: main
    icon: mdi:information-outline
    cards:
      - type: glance
        entities:
          - device_tracker.paulus
          - device_tracker.anne_there
