resources:
  - url: /local/simple-thermostat.js
    type: module

title: Edenbridge
views:  
  - title: main
    path: main
    icon: mdi:information-outline
    cards:
      - type: entities
        title: Who´s at Home
        entities:
          - person.faye_dawson
          - person.richard_dawson

      - type: entities
        title: Sensor´s 
        entities:
          - input_datetime.rd_android_alarm
      
      - type: entities
        title: Sensor´s 
        entities:
          - sun.sun
          - sensor.us_pirs
          - sensor.ds_pirs
          - sensor.out_side_lux
          - input_select.house_mode
      
      - type: entities
        title: Outside Movement 
        entities:
          - binary_sensor.backgarden_movement
          - binary_sensor.coop_movement
          - binary_sensor.driveway_movement
          - binary_sensor.porch_movement
          - binary_sensor.sidedrive_movement
      
      - type: entities
        title: Edenbridge Temp´s
        entities:
          - sensor.outside_temperature
          - sensor.downstairs_temperature
          - sensor.upstairs_temperature
              
  - title: Heating
    icon: mdi:radiator
    path: heating
    cards:
      - type: 'custom:simple-thermostat'
        entity: climate.downstairs
        step_size: 1
        sensors:
          - entity: sensor.playroom_s_room_humidity
            name: Humidity
      - type: 'custom:simple-thermostat'
        entity: climate.upstairs
        step_size: 1
        sensors:
          - entity: sensor.playroom_s_room_humidity
            name: Humidity
      - type: 'custom:simple-thermostat'
        entity: climate.kitchen
        step_size: 1
        sensors:
          - entity: sensor.kitchen_humidity
            name: Humidity
    
          
      - type: vertical-stack  
        cards:

          - type: entities
            title: Heating Control´s 
            entities:
              - switch.downstairs_radiators
              - switch.upstairs_radiators
              - binary_sensor.cylinder_thermostats
              - switch.underfloor_heating
              - switch.hotwater
              - switch.boiler_call

  - title: Rooms
    path: rooms
    icon: mdi:home-outline

    cards:
      - type: glance
        title: Master bedroom 
        entities:
          - entity: light.master_bedroom_light
          - entity: light.faye_s_bedside_lamp
          - entity: light.rich_s_bedside_lamp
          - entity: light.master_bedroom_bedside_lamps
          - entity: binary_sensor.raf_s_pir
          - entity: sensor.master_room_temperature

      - type: glance
        title: Lila´s bedroom 
        entities:
          - entity: light.lila_s_bedroom_light
          - entity: binary_sensor.lila_s_pir
          - entity: sensor.lila_room_temperature
          
      - type: glance
        title: Thea´s bedroom 
        entities:
          - entity: light.thea_s_bedroom_light
          - entity: binary_sensor.thea_s_bedroom_pir
          - entity: sensor.thea_room_temperature
          
      - type: glance
        title: Playroom 
        entities:
          - entity: light.playrooms_light
          - entity: binary_sensor.playroom_pir
          - entity: light.globe_lamp
          - entity: switch.tv
          - entity: sensor.playroom_s_room_temperature
          
      - type: glance
        title: Lounge 
        entities:
          - entity: light.lounge_bookshelf_lights
          - entity: light.lounge_lights
          - entity: binary_sensor.lounge_pir
          - entity: light.fairy_lights_telescope
          - entity: sensor.lounge_temperature
          
      - type: glance
        title: Kitchen 
        entities:
          - entity: light.kitchen_dining_lights
          - entity: light.kitchen_side_lights
          - entity: light.kitchen_island_lights
          - entity: light.kitchen_fairy_lights
          - entity: binary_sensor.kitchen_pir
          - entity: light.boiler_lamp
          - entity: sensor.kitchen_temperature
          - entity: sensor.underfloor_temperature


      - type: glance
        title: Landing / Hallway
        entities:
          - entity: light.landing_lights
          - entity: light.hallway_lights
          - entity: sensor.landing_temperature

      - type: glance
        title: Garage
        entities:
          - entity: binary_sensor.garage_door
          - entity: switch.garage_door_lock
          - entity: light.garage_lights
          - entity: sensor.driveway
          
      - type: glance
        title: Back garden
        entities:
          - entity: binary_sensor.garden_gate 
          - entity: light.garden_lights
          
      - type: glance
        title: Front garden
        entities:
          - entity: light.porch_light
          - entity: binary_sensor.frontgarden_gate
          - entity: binary_sensor.front_door
          - entity: sensor.porch

      - type: glance
        title: Bathroom
        entities:
          - entity: light.bathroom_mirror
          - entity: light.bathroom
          - entity: binary_sensor.bathroom_switch
          - entity: binary_sensor.bathroom_mirror_switch
          - entity: switch.bathroom_extractor_fan
          - entity: sensor.bathroom_humidity
          - entity: sensor.bathroom_temperature
      
      - type: glance
        title: Downstairs toilet 
        entities:
          - entity: switch.downstairs_toilet_extractor_fan
          - entity: sensor.downstairs_toilet_humidity
          - entity: sensor.downstairs_toilet_temperature



  
  - title: Master's Switch's
    icon: mdi:toggle-switch
    path: switchs
    cards:
      - type: glance
        entities:
          - entity: input_boolean.coop_cleanning
          - entity: input_boolean.guest_room
          - entity: input_boolean.eating_mode

  - title: Media
    path: Media
    icon: mdi:music
    cards:
      - type: glance
        title: TV players
        entities:
          - entity: media_player.playroom
      
      - type: glance
        title: Music players
        entities:
          - entity: media_player.lounge
          - entity: media_player.garden
          - entity: media_player.kitchen
          - entity: media_player.kitchen_2
          - entity: media_player.master_bedroom
          - entity: media_player.thea_bedroom
          - entity: media_player.lila_bedroom

  - title: Chickhen´s
    path: chickhens
    icon: mdi:bird
    cards:
      - type: glance
        entities:
          - entity: switch.coop_door_close
          - entity: switch.coop_door_open
          - entity: binary_sensor.chickens_coop_door
          - entity: binary_sensor.chickens_garden_door
 
  - title: Christmas
    path: Christmas
    icon: mdi:string-lights
    cards:
      - type: glance
        title: Fiary light's power
        entities:
          - entity: group.christmas_lights_psu
          - entity: switch.mega_tree_r_psu1
          - entity: switch.mega_tree_r_psu2
          - entity: switch.lounge_windows_led_psu
          - entity: switch.smallbedroom_windows_led_psu
          - entity: switch.front_bush_led_psu
      
      - type: glance
        title: WLED Controllers
        entities:
          - entity: light.front_christmas_lights
          - entity: light.frontbush_node_242
          - entity: light.frontbushr_node_243
          - entity: light.smallbedroom_node_244
          - entity: light.loungewindow_node_245
          - entity: light.megatrnode_247
          - entity: light.megatrnode_248
          - entity: light.megatrnode_249
          - entity: light.megatrnode_250
  
