- id: '1000'
  alias: Gone out switch lights and power off
  trigger:
    - platform: state
      entity_id: sensor.all_pirs
      to: 'true'
      for: '00:10:00'
  condition:
    condition: not
    conditions:
      - condition: state
        entity_id: group.persons
        state: 'home'
  action:
    - service: light.turn_off
      entity_id: all
    - service: homeassistant.turn_off
      entity_id:
        - switch.dishwasher
        - switch.washing_machine
        - switch.tumble_dryer

- id: '1001'
  alias: Home turn on appances
  trigger:
    - platform: state
      entity_id: group.persons
      from: 'not_home'
      to: 'home'
  condition:
    condition: not
    conditions:
      - condition: state
        entity_id: input_boolean.night_mode
        state: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id:
        - switch.dishwasher
        - switch.washing_machine
        - switch.tumble_dryer

- id: '1002'
  alias: Someone has entered house perimeter (no one is home)
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.porch_movement
        - binary_sensor.backgarden_movement
        - binary_sensor.driveway_movement
      to: 'on'
  condition:
    condition: not
    conditions:
      - condition: state
        entity_id: group.persons
        state: 'home'
  action:
    - service: notify.mobile_app_rich_phone
      data:
        message: >
          Everyone is out: At {{states('sensor.time')}} movement on {{trigger.to_state.name}} camera!

