- id: '100'
  alias: Notification Time for School
  trigger:
    - platform: time
      at: '07:30:00'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: notify.alexa_media
      data: 
        message: Good morning Thea & Lila, it's time to get up for school, don't forget to do your chores
        target:
          - media_player.Lila_bedroom
          - media_player.Thea_bedroom
        data:
          type: announce