####################################
## Hallway light switch on by PIR ##
####################################

- id: '1100'
  alias: 'Lights Hallway Main'
  trigger:
    - platform: state
      entity_id: binary_sensor.hallway_pir
      to: "on"
      id: "pir_light_hallway_on"
    - platform: state
      entity_id: binary_sensor.hallway_pir
      to: "off"
      for: '00:02:00'
      id: "pir_light_hallway_off"
  action:
    - choose:
        - conditions:
            - condition: trigger
              id: "pir_light_hallway_on"
            - condition: state
              entity_id: binary_sensor.enable_auto_lights
              state: "on"
          sequence:
            - service: light.turn_on
              target:
                entity_id: light.hallway_light_s
    - choose:
        - conditions:
            - condition: trigger
              id: "pir_light_hallway_off"
            - condition: state
              entity_id: light.hallway_light_s
              state: "on"
          sequence:
            - service: light.turn_off
              target:
                entity_id: light.hallway_light_s

####################
## Playroom light ##
####################


- id: '1101'
  alias: 'Lights Playroom main'
  trigger:
    - platform: state
      entity_id: binary_sensor.playroom_pir
      to: "on"
      id: "pir_light_playroom_on"
    - platform: state
      entity_id: binary_sensor.playroom_pir
      to: "off"
      for: '00:02:00'
      id: "pir_light_playroom_off"
  action:
    - choose:
        - conditions:
            - condition: trigger
              id: "pir_light_playroom_on"
            - condition: state
              entity_id: binary_sensor.enable_auto_lights
              state: "on"
            - condition: state
              entity_id: input_boolean.guest_room
              state: 'off'
          sequence:
            - service: light.turn_on
              target:
                entity_id: light.playroom_light_s
    - choose:
        - conditions:
            - condition: trigger
              id: "pir_light_playroom_off"
            - condition: state
              entity_id: light.playroom_light_s
              state: "on"
          sequence:
            - service: light.turn_off
              target: 
                entity_id: light.playroom_light_s


####################
## Landing lights ##
####################

- id: '1102'
  alias: 'Lights Landing Main'
  trigger:
    - platform: state
      entity_id: binary_sensor.landing_pir
      to: "on"
      id: "pir_light_landing_on"
    - platform: state
      entity_id: binary_sensor.landing_pir
      to: "off"
      for: '00:02:00'
      id: "pir_light_landing_off"
  action:
    - choose:
        - conditions:
            - condition: trigger
              id: "pir_light_landing_on"
            - condition: state
              entity_id: binary_sensor.enable_auto_lights
              state: "on"
          sequence:
            - service: light.turn_on
              target: 
                entity_id: light.landing_lights
    - choose:
        - conditions:
            - condition: trigger
              id: "pir_light_landing_off"
            - condition: state
              entity_id: light.landing_lights
              state: "on"
          sequence:
            - service: light.turn_off
              target: 
                entity_id: light.landing_lights


###############################################################
## Lila´s Room
###############################################################


- id: '1103'
  alias: 'Lights Lila Main'
  trigger:
    - platform: state
      entity_id: binary_sensor.lila_bedroom_pir
      to: "on"
      id: "pir_light_lila_on"
    - platform: state
      entity_id: binary_sensor.lila_bedroom_pir
      to: "off"
      for: '00:02:00'
      id: "pir_light_lila_off"
  action:
    - choose:
        - conditions:
            - condition: trigger
              id: "pir_light_lila_on"
            - condition: state
              entity_id: binary_sensor.enable_auto_lights
              state: "on"
            - condition: time
              before: "18:30:00"
              after: "08:30:00"
          sequence:
            - service: light.turn_on
              target: 
                entity_id: light.lila_s_bedroom_light
    - choose:
        - conditions:
            - condition: trigger
              id: "pir_light_lila_off"
            - condition: state
              entity_id: light.lila_s_bedroom_light
              state: "on"
            - condition: state
              entity_id: switch.lila_bedroom_do_not_disturb_switch
              state: "off"
          sequence:
            - service: light.turn_off
              target: 
                entity_id: light.lila_s_bedroom_light

###############################################################
## Thea´s Room
###############################################################


- id: '1104'
  alias: 'Lights Thea Main'
  trigger:
    - platform: state
      entity_id: binary_sensor.thea_s_bedroom_pir
      to: "on"
      id: "pir_light_thea_on"
    - platform: state
      entity_id: binary_sensor.thea_s_bedroom_pir
      to: "off"
      for: '00:02:00'
      id: "pir_light_thea_off"
  action:
    - choose:
        - conditions:
            - condition: trigger
              id: "pir_light_thea_on"
            - condition: state
              entity_id: binary_sensor.enable_auto_lights
              state: "on"
            - condition: time
              before: "18:30:00"
              after: "08:30:00"
          sequence:
            - service: light.turn_on
              target: 
                entity_id: light.thea_s_bedroom_light
        - conditions:
            - condition: trigger
              id: "pir_light_thea_off"
            - condition: state
              entity_id: light.thea_s_bedroom_light
              state: "on"
            - condition: state
              entity_id: switch.thea_bedroom_do_not_disturb_switch
              state: "off"
          sequence:
            - service: light.turn_off
              target: 
                entity_id: light.thea_s_bedroom_light



###############################################################
## Master bedroom
###############################################################

- id: '1105'
  alias: Motion Sensor Masterbedroom Off
  trigger:
    - platform: state
      entity_id: binary_sensor.master_bedroom_pir
      to: 'off'
      for: '00:02:00'
  condition:
    - condition: state
      entity_id:
        - light.master_bedroom_light
      state: 'on'
  action:
    - service: light.turn_off
      target: 
        entity_id: light.master_bedroom_light



###############################################################
## Lounge
###############################################################

- id: '1106'
  alias: 'Lights lounge Main'
  trigger:
    - platform: state
      entity_id: binary_sensor.lounge_pir
      to: "off"
      for: '00:05:00'
      id: "pir_lounge_off"
    - platform: state
      entity_id: binary_sensor.lounge_pir
      to: "on"
      id: "pir_lounge_on"
  action:
    - choose:
        - conditions:
            - condition: trigger
              id: "pir_lounge_off"
            - condition: state
              entity_id: light.lounge_main_light
              state: "on"
          sequence:
            - service: light.turn_on
              target: 
                entity_id: light.lounge_main_light
        - conditions:
            - condition: trigger
              id: "pir_lounge_on"
            - condition: state
              entity_id: binary_sensor.enable_auto_lights
              state: "on"
          sequence:
            - service: light.turn_on
              target: 
                entity_id: light.lounge_main_light


###############################################################
## Kitchen
###############################################################

- id: '1107'
  alias: No-motion kitchen light
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_pir
      to: 'off'
      for: '00:01:00'
  condition:
    - condition: or
      conditions:
      - condition: state
        entity_id: light.kitchen_dining
        state: 'on'
      - condition: state
        entity_id: light.kitchen_island
        state: 'on'
      - condition: state
        entity_id: light.side_lights
        state: 'on'
  action:
    - service: light.turn_off
      target: 
        entity_id:
          - light.kitchen_dining
          - light.kitchen_island
          - light.side_lights



