####################################
## Hallway light switch on by PIR ##
####################################

- id: '1100'
  alias: 'Lights Hallway Main'
  trigger:
    - platform: state
      entity_id: binary_sensor.hallway_pir
      to: "on"
      id: "pir_light_hallway_on"
    - platform: state
      entity_id: binary_sensor.hallway_pir
      to: "off"
      for: '00:02:00'
      id: "pir_light_hallway_off"
  action:
    - choose:
        - conditions:
            - condition: trigger
              id: "pir_light_hallway_on"
            - condition: state
              entity_id: binary_sensor.enable_auto_lights
              state: "on"
          sequence:
            - service: light.turn_on
              target:
                entity_id: light.hallway_lights
    - choose:
        - conditions:
            - condition: trigger
              id: "pir_light_hallway_off"
            - condition: state
              entity_id: light.hallway_lights
              state: "on"
          sequence:
            - service: light.turn_off
              target:
                entity_id: light.hallway_lights

####################
## Playroom light ##
####################


- id: '1101'
  alias: 'Lights Playroom main'
  trigger:
    - platform: state
      entity_id: binary_sensor.espresense_playroon_motion
      to: "on"
      id: "pir_light_playroom_on"
    - platform: state
      entity_id: binary_sensor.espresense_playroon_motion
      to: "off"
      for: '00:02:00'
      id: "pir_light_playroom_off"
  action:
    - choose:
        - conditions:
            - condition: trigger
              id: "pir_light_playroom_on"
            - condition: state
              entity_id: binary_sensor.enable_auto_lights
              state: "on"
            - condition: state
              entity_id: input_boolean.guest_room
              state: 'off'
          sequence:
            - service: light.turn_on
              target:
                entity_id: light.playroom_s_light
    - choose:
        - conditions:
            - condition: trigger
              id: "pir_light_playroom_off"
            - condition: state
              entity_id: light.playroom_s_light
              state: "on"
          sequence:
            - service: light.turn_off
              target: 
                entity_id: light.playroom_s_light


####################
## Landing lights ##
####################

- id: '1102'
  alias: 'Lights Landing Main'
  trigger:
    - platform: state
      entity_id: binary_sensor.landing_pir
      to: "on"
      id: "pir_light_landing_on"
    - platform: state
      entity_id: binary_sensor.landing_pir
      to: "off"
      for: '00:02:00'
      id: "pir_light_landing_off"
  action:
    - choose:
        - conditions:
            - condition: trigger
              id: "pir_light_landing_on"
            - condition: state
              entity_id: binary_sensor.enable_auto_lights
              state: "on"
          sequence:
            - service: light.turn_on
              target: 
                entity_id: light.landing_lights
    - choose:
        - conditions:
            - condition: trigger
              id: "pir_light_landing_off"
            - condition: state
              entity_id: light.landing_lights
              state: "on"
          sequence:
            - service: light.turn_off
              target: 
                entity_id: light.landing_lights


###############################################################
## Lila´s Room
###############################################################


- id: '1103'
  alias: 'Lights Lila Main'
  trigger:
    - platform: state
      entity_id: binary_sensor.lila_s_pir
      to: "on"
      id: "pir_light_lila_on"
    - platform: state
      entity_id: binary_sensor.lila_s_pir
      to: "off"
      for: '00:02:00'
      id: "pir_light_lila_off"
  action:
    - choose:
        - conditions:
            - condition: trigger
              id: "pir_light_lila_on"
            - condition: state
              entity_id: binary_sensor.enable_auto_lights
              state: "on"
            - condition: state
              entity_id: sensor.kids_bedtime
              state: 'off'
          sequence:
            - service: light.turn_on
              target: 
                entity_id: light.lila_s_bedroom_light
    - choose:
        - conditions:
            - condition: trigger
              id: "pir_light_lila_off"
            - condition: state
              entity_id: light.lila_s_bedroom_light
              state: "on"
            - condition: state
              entity_id: switch.lila_bedroom_do_not_disturb_switch
              state: "off"
          sequence:
            - service: light.turn_off
              target: 
                entity_id: light.lila_s_bedroom_light

###############################################################
## Thea´s Room
###############################################################


- id: '1104'
  alias: 'Lights Thea Main'
  trigger:
    - platform: state
      entity_id: binary_sensor.thea_s_bedroom_pir
      to: "on"
      id: "pir_light_thea_on"
    - platform: state
      entity_id: binary_sensor.thea_s_bedroom_pir
      to: "off"
      for: '00:02:00'
      id: "pir_light_thea_off"
  action:
    - choose:
        - conditions:
            - condition: trigger
              id: "pir_light_lila_on"
            - condition: state
              entity_id: binary_sensor.enable_auto_lights
              state: "on"
            - condition: state
              entity_id: sensor.kids_bedtime
              state: 'off'
          sequence:
            - service: light.turn_on
              target: 
                entity_id: light.thea_s_bedroom_light
    - choose:
        - conditions:
            - condition: trigger
              id: "pir_light_lila_off"
            - condition: state
              entity_id: light.lila_s_bedroom_light
              state: "on"
            - condition: state
              entity_id: switch.thea_bedroom_do_not_disturb_switch
              state: "off"
          sequence:
            - service: light.turn_off
              target: 
                entity_id: light.thea_s_bedroom_light



###############################################################
## Master bedroom
###############################################################

- id: '1106'
  alias: Motion Sensor Masterbedroom Off
  trigger:
    - platform: state
      entity_id: binary_sensor.raf_s_pir
      to: 'off'
      for: '00:02:00'
  condition:
    - condition: state
      entity_id:
        - light.master_bedroom_light
      state: 'on'
  action:
    - service: light.turn_off
      target: 
        entity_id: light.master_bedroom_light



###############################################################
## Lounge
###############################################################



###############################################################
## Kitchen
###############################################################

- id: '1110'
  alias: No-motion kitchen light
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_pir
      to: 'off'
      for: '00:02:00'
  condition:
    - condition: or
      conditions:
      - condition: state
        entity_id: light.kitchen_dining
        state: 'on'
      - condition: state
        entity_id: light.kitchen_island
        state: 'on'
      - condition: state
        entity_id: light.kitchen_side_lights
        state: 'on'
  action:
    - service: light.turn_off
      target: 
        entity_ids:
          - light.kitchen_dining
          - light.kitchen_island
          - light.kitchen_side_lights