###############################################################
## Hallway light switch on by PIR
################################################################

- id: '1100'
  alias: 'Motion hallway light'
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.hallway_pir
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: binary_sensor.enable_auto_lights
      state: "on"
  action:
      - service: light.turn_on
        entity_id:
          - light.hallway_lights
      - wait_for_trigger:
          platform: state
          entity_id:
            - binary_sensor.hallway_pir
          to: "off"
          for: 00:02:00
      - service: light.turn_off
        entity_id:
          - light.hallway_lights
  mode: restart
  max_exceeded: silent


###############################################################
## Hallway light switch on by Switch
################################################################

- id: '1111'
  alias: 'Hallway light switch on by Switch'
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.hallway_lights_switch
  action:
      - wait_for_trigger:
          platform: state
          entity_id:
            - binary_sensor.hallway_pir
          to: "off"
          for: 00:02:00
      - condition: state
        entity_id: light.hallway_lights
        state: 'on'
      - service: light.turn_off
        entity_id:
          - light.hallway_lights
  mode: restart
  max_exceeded: silent



###############################################################
## Playroom
###############################################################

- id: '1102'
  alias: Motion Sensor Playroom On
  trigger:
    - platform: state
      entity_id: binary_sensor.playroom_pir
      to: 'on'
  condition:
    - condition: state
      entity_id:
        - light.globe_lamp
        - input_boolean.guest_room
      state: 'off'
    - condition: or
      conditions:
        - condition: state
          entity_id: input_boolean.night_mode
          state: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: light.playroom_s_light

- id: '1103'
  alias: Motion Sensor Playroom Off
  trigger:
    - platform: state
      entity_id: binary_sensor.playroom_pir
      to: 'off'
      for:
        minutes: 5
  condition:
    - condition: state
      entity_id: input_boolean.guest_room
      state: 'off'
  action:
    - service: homeassistant.turn_off
      entity_id: light.playroom_s_light


###############################################################
## Landing
###############################################################


- id: '1104'
  alias: 'Motion landing light'
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.landing_pir
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: binary_sensor.enable_auto_lights
      state: "on"
  action:
    - service: light.turn_on
      entity_id:
        - light.landing_lights
    - wait_for_trigger:
        platform: state
        entity_id:
          - binary_sensor.landing_pir
        from: "on"
        to: "off"
    - delay: 00:02:00
    - service: light.turn_off
      entity_id:
        - light.landing_lights
  mode: restart
  max_exceeded: silent


###############################################################
## Lila´s Room
###############################################################

- id: '1106'
  alias: Motion Sensor Lila Off
  trigger:
    - platform: state
      entity_id: binary_sensor.lila_s_pir
      to: 'off'
      for:
        minutes: 10
  condition:
    - condition: state
      entity_id:
        - light.lila_s_bedroom_light
      state: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: light.lila_s_bedroom_light

###############################################################
## Thea´s Room
###############################################################

- id: '1107'
  alias: Motion Sensor Thea Off
  trigger:
    - platform: state
      entity_id: binary_sensor.thea_s_bedroom_pir
      to: 'off'
      for:
        minutes: 10
  condition:
    - condition: state
      entity_id:
        - light.thea_s_bedroom_light
      state: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: light.thea_s_bedroom_light



###############################################################
## Master bedroom
###############################################################

- id: '1108'
  alias: Motion Sensor Masterbedroom Off
  trigger:
    - platform: state
      entity_id: binary_sensor.raf_s_pir
      to: 'off'
      for:
        minutes: 5
  condition:
    - condition: state
      entity_id:
        - light.master_bedroom_light
      state: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id:
        - light.master_bedroom_light



###############################################################
## Lounge
###############################################################



###############################################################
## Kitchen
###############################################################

- id: '1110'
  alias: No-motion kitchen light
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_pir
      to: 'off'
      for:
        minutes: 5
  condition:
    - condition: or
      conditions:
      - condition: state
        entity_id: light.kitchen_dining
        state: 'on'
      - condition: state
        entity_id: light.kitchen_island
        state: 'on'
      - condition: state
        entity_id: light.kitchen_side_lights
        state: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id:
        - light.kitchen_dining
        - light.kitchen_island
        - light.kitchen_side_lights