- id: '1300'
  alias: Morning time Kitchen
  trigger:
    - platform: time
      at:
        - sensor.sm_faye_next_alarm
        - sensor.sm_g991b_next_alarm
  condition:
    - condition: template
      value_template: "{{ state_attr('sun.sun','rising') == true }}"
  action:
    - wait_for_trigger:
      - platform: state
        entity_id: binary_sensor.hallway_pir
        to: "on"
      timeout: "02:00:00"
      continue_on_timeout: false
    - service: media_player.play_media
      target:
        entity_id: media_player.kitchen
      data:
        media_content_id: FV:2/7
        media_content_type: favorite_item_id
      metadata:
        title: Virgin Radio UK
        thumbnail: >-
          https://d1uner0r1fcap8.cloudfront.net/image?w=60&image=https%3A%2F%2Fcdn-profiles.tunein.com%2Fs266113%2Fimages%2Flogog.png%3Ft%3D1&partnerId=tunein
        media_class: genre
        children_media_class: null
        navigateIds:
          - {}
          - media_content_type: favorites
            media_content_id: ''
          - media_content_type: favorites_folder
            media_content_id: object.item.audioItem.audioBroadcast
    - service: media_player.volume_set
      data:
        volume_level: 0.22
      target:
        entity_id: media_player.kitchen
    - service: scene.turn_on
      target:
        entity_id: scene.appliances_on