- id: "1400"
  alias: Night mode enabled
  trigger:
    - platform: state
      id: "nightbed"
      entity_id:
        - input_boolean.richinbed
        - input_boolean.fayeinbed
      to: "on"
      for: "00:15:00"
    - platform: state
      id: "awaynightmode"
      entity_id: binary_sensor.enable_auto_lights
      to: "on"
      for:
        hours: 5
  action:
    - choose:
        - conditions:
            - condition: trigger
              id: "nightbed"
            - condition: state
              entity_id: binary_sensor.no_activity_downstairs
              state: "on"
              for:
                minutes: 5
            - condition: state
              entity_id: binary_sensor.enable_auto_lights
              state: "on"
            - condition: time
              after: "20:00:00"
              before: "03:00:00"
            - condition: not
              conditions:
                - condition: state
                  entity_id: media_player.lounge
                  state: "playing"
          sequence:
            - service: input_boolean.turn_on
              target:
                entity_id: input_boolean.night_mode
            - service: light.turn_off
              data: {}
              target:
                area_id:
                  - garden
                  - kitchen
                  - hallway
                  - main_bathroom
                  - playroom
                  - thea_bedroom
                  - lounge
                  - landing
                  - lila_bedroom
                  - office
            - service: scene.turn_on
              target:
                entity_id: scene.nightmode
              metadata: {}
              

        - conditions:
            - condition: trigger
              id: "awaynightmode"
            - condition: state
              entity_id: group.persons
              state: "not_home"
          sequence:
            - service: input_boolean.turn_on
              target:
                entity_id: input_boolean.night_mode
            - service: light.turn_off
              data: {}
              target:
                area_id:
                  - garden
                  - kitchen
                  - hallway
                  - main_bathroom
                  - playroom
                  - thea_bedroom
                  - lounge
                  - landing
                  - lila_bedroom
                  - office
            - service: scene.turn_on
              target:
                entity_id: scene.nightmode
              metadata: {}
              
              

- id: "1401"
  alias: Out hours movment
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.porch_movement
        - binary_sensor.backgarden_movement
        - binary_sensor.coop_movement
        - binary_sensor.driveway_movement
        - binary_sensor.sidedrive_movement
      to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.night_mode
      state: 'on'
  action:
    - service: notify.mobile_app_rich_phone
      data:
        message: >
          Night mode enabled: At {{states("sensor.time")}} movement on {{trigger.to_state.name}} camera!