- id: 1601
  alias: Disable Gate left open
  trigger:
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: "back_gate_alarm"
  action:
    - service: alert.turn_off
      target:
        entity_id: alert.garden_gate


- id: 1602
  alias: Notify of events
  trigger:
    - platform: mqtt
      topic: frigate/events
  condition:
    - condition: state
      entity_id: group.persons
      state: 'not_home'
  action:
    - service: notify.mobile_app_rich_phone
      data_template:
        message: 'A {{trigger.payload_json["after"]["label"]}} was detected.'
        data:
          photo:
            # this url should work for addon users
            - url: 'http://interfrigate:5000/api/events/{{trigger.payload_json["after"]["id"]}}/thumbnail.jpg'
              caption: 'A {{trigger.payload_json["after"]["label"]}} was detected on {{ trigger.payload_json["after"]["camera"] }} camera'