- id: '1601'
  alias: Disable Gate left open
  trigger:
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: "back_gate_alarm"
  action:
    - service: alert.turn_off
      target:
        entity_id: alert.garden_gate


- id: '1602'
  alias: Notify of events in driveway
  trigger:
    - platform: mqtt
      topic: frigate/events
  condition:
    - condition: state
      entity_id: group.persons
      state: 'not_home'
    - "{{ trigger.payload_json['after']['label'] == 'person' }}"
    - "{{ 'drive' in trigger.payload_json['after']['entered_zones'] }}"
  action:
    - service: notify.mobile_app_rich_phone
      data_template:
        message: 'A {{trigger.payload_json["after"]["label"]}} was detected.'
        data:
            image: 'http:/frigate:5000/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/thumbnail.jpg?format=android'
            tag: '{{trigger.payload_json["after"]["id"]}}'
            when: '{{trigger.payload_json["after"]["start_time"]|int}}'

- id: '1603'
  alias: Notify of events in porch
  trigger:
    - platform: mqtt
      topic: frigate/events
  condition:
    - condition: state
      entity_id: group.persons
      state: 'not_home'
    - "{{ trigger.payload_json['after']['label'] == 'person' }}"
    - "{{ 'porch_path_a' in trigger.payload_json['after']['entered_zones'] }}"
  action:
    - service: notify.mobile_app_rich_phone
      data_template:
        message: 'A {{trigger.payload_json["after"]["label"]}} was detected.'
        data:
            image: 'http:/frigate:5000/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/thumbnail.jpg?format=android'
            tag: '{{trigger.payload_json["after"]["id"]}}'
            when: '{{trigger.payload_json["after"]["start_time"]|int}}'