- id: '300'
  alias: Awake+lights motion master bathroom
  trigger:
  - platform: state
    entity_id: binary_sensor.bathroom_main_light_switch
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id:
          - light.bathroom_main_light
        state: 'off'
      - condition: state
        entity_id:
          - binary_sensor.enable_auto_lights
        state: 'on'
      - condition: state
        entity_id:
          - input_boolean.night_mode
        state: 'off'
  action:
  - service: homeassistant.turn_on
    entity_id: light.bathroom_main_light

- id: '301'
  alias: Night motion master bathroom
  trigger:
  - platform: state
    entity_id: binary_sensor.bathroom_main_light_switch
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.bathroom_mirror
        state: 'off'
      - condition: state
        entity_id: input_boolean.night_mode
        state: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: light.bathroom_mirror

- id: '302'
  alias: No motion master bathroom
  trigger:
  - platform: state
    entity_id: binary_sensor.bathroom_main_light_switch
    to: 'off'
  condition:
    condition: or
    conditions: 
      - condition: state
        entity_id: light.bathroom_main_light
        state: 'on'
      - condition: state
        entity_id: light.bathroom_mirror
        state: 'on'
  action:
  - service: homeassistant.turn_off
    entity_id: 
      - light.bathroom_main_light
      - light.bathroom_mirror

- id: '303'
  alias: Upstairs Bathroom Extractor needed
  trigger:
  - entity_id: binary_sensor.upstairs_bath_fan
    for: 00:00:30
    platform: state
  condition: []
  action:
  - data:
      entity_id: switch.bathroom_extractor_fan
    service_template: switch.turn_{{trigger.to_state.state}}

- id: '304'
  alias: Downstairs Bathroom Extractor needed
  trigger:
  - entity_id: binary_sensor.downst_bath_fan
    for: 00:00:30
    platform: state
  condition: []
  action:
  - data:
      entity_id: switch.downstairs_toilet_extractor_fan
    service_template: switch.turn_{{trigger.to_state.state}}
