- id: '300'
  alias: Awake+lights motion master bathroom
  trigger:
  - platform: state
    entity_id: binary_sensor.bathroom_main_light_switch
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id:
          - light.bathroom_main_light
        state: 'off'
      - condition: state
        entity_id:
          - binary_sensor.enable_auto_lights
        state: 'on'
      - condition: state
        entity_id:
          - input_boolean.night_mode
        state: 'off'
  action:
  - service: homeassistant.turn_on
    entity_id: light.bathroom_main_light

- id: '301'
  alias: Night motion master bathroom
  trigger:
  - platform: state
    entity_id: binary_sensor.bathroom_main_light_switch
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.bathroom_mirror
        state: 'off'
      - condition: state
        entity_id: input_boolean.night_mode
        state: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: light.bathroom_mirror

- id: '302'
  alias: No motion master bathroom
  trigger:
  - platform: state
    entity_id: binary_sensor.bathroom_main_light_switch
    to: 'off'
  condition:
    condition: or
    conditions: 
      - condition: state
        entity_id: light.bathroom_main_light
        state: 'on'
      - condition: state
        entity_id: light.bathroom_mirror
        state: 'on'
  action:
  - service: homeassistant.turn_off
    entity_id: 
      - light.bathroom_main_light
      - light.bathroom_mirror

- id: '303'
  alias: Bathroom Extractor needed
  trigger:
  - platform: state
    entity_id: sensor.m_broom_th_4aeb_humidity
  condition:
    - condition: template
      value_template: >
        {{ trigger.from_state.state | is_number and trigger.to_state.state | is_number and trigger.to_state.state / trigger.from_state.state >= 1.1 }}
  action: 
    - service: homeassistant.turn_on
      entity_id: switch.bathroom_extractor_fan
    - wait_for_trigger:
        - platform: numeric_state
          entity_id: sensor.bathroom_humidity
          below: '75'
          for: '00:05'
    - service: homeassistant.turn_off
      entity_id: switch.bathroom_extractor_fan
  mode: restart


- id: '304'
  alias: Downstairs Bathroom Extractor needed
  trigger:
    - platform: numeric_state
      entity_id: sensor.downstairs_toilet_humidity
      above: '90'
  condition: []
  action:
    - service: homeassistant.turn_on
      entity_id: switch.downstairs_toilet_extractor_fan
    - wait_for_trigger:
        - platform: numeric_state
          entity_id: sensor.downstairs_toilet_humidity
          below: '85'
          for: '00:05'
    - service: homeassistant.turn_off
      entity_id: switch.downstairs_toilet_extractor_fan
  mode: restart