- id: '700'
  alias: Evening with lights
  trigger:
    - platform: state
      entity_id: binary_sensor.enable_auto_lights
      from: 'off'
      to: 'on'
      for: "00:05:00"

  condition:
    - condition: template
      value_template: "{{ state_attr('sun.sun','rising') == false }}"
    - condition: not
      conditions:
        - condition: state
          entity_id: input_boolean.night_mode
          state: "on"
  action:
    - service: scene.turn_on
      data: {}
      target: 
        entity_id: scene.evening_lights

- id: '701'
  alias: Christmas ligths on
  trigger: 
    - platform: time
      at: "16:30:00"
  action:
    - service: homeassistant.turn_on
      entity_id:
        - switch.mega1
        - switch.mega2


- id: '702'
  alias: Christmas ligths off
  trigger: 
    - platform: time
      at: "00:00:00"
  action:
    - service: homeassistant.turn_off
      entity_id:
        - switch.mega1
        - switch.mega2
        
        

