###################################################
## Open and Closing garage door ##
###################################################
- id: '800'
  alias: Garage door unlock
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_door
      to: 'on'
  condition:
    - condition: state
      entity_id: group.persons
      state: 'home'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.office_door_lock

