- id: '900'
  alias: Heating >> Boiler on/off
  trigger:
    - platform: template
      id: "heatingcall"
      value_template: >
        {{ is_state('switch.downstairs_radiators', 'on') or
          is_state('switch.upstairs_radiators', 'on') or
          is_state('switch.underfloor_heating', 'on')
        }}
    - platform: template
      id: "nonheating"
      value_template: >
        {{ is_state('switch.downstairs_radiators', 'off') and
          is_state('switch.underfloor_heating', 'off') and
          is_state('switch.upstairs_radiators', 'off') and
          is_state('switch.hotwater', 'off')
        }}
    - platform: state
      id: "hotwater"
      entity_id: switch.hotwater
      to: 'on'
  action:
    - choose:
        - conditions:
            - condition: trigger
              id: "heatingcall"
            - condition: state
              entity_id: switch.boiler_call
              state: "off"
            - condition: state
              entity_id: group.persons
              state: "home"
          sequence:
            - service: homeassistant.turn_on
              target:
                entity_id:
                  - switch.boiler_call
        - conditions:
            - condition: trigger
              id: "hotwater"
            - condition: state
              entity_id: switch.boiler_call
              state: "off"
            - condition: time
              after: "04:25:00"
              before: "23:00:00"
            - condition: state
              entity_id: group.persons
              state: "home"
          sequence:
            - service: homeassistant.turn_on
              target:
                entity_id:
                  - switch.boiler_call
        - conditions:
            - condition: trigger
              id: "nonheating"
            - condition: state
              entity_id: switch.boiler_call
              state: "on"
          sequence:
            - service: homeassistant.turn_off
              target:
                entity_id:
                  - switch.boiler_call
  mode: single

- id: '901'
  alias: Heating >> Home/Not home
  trigger:
    - platform: state
      id: "homeheating"
      entity_id: group.persons
      to: "home"
    - platform: state
      id: "nothomeheating"
      entity_id: group.persons
      to: "not_home"
      for: "01:00:00"
  action:
    - choose:
        - conditions:
            - condition: trigger
              id: "nothomeheating"
          sequence:
            - service: climate.set_preset_mode
              data:
                preset_mode: away
              target:
                entity_id:
                  - climate.upstairs
                  - climate.downstairs
                  - climate.office
                  - climate.kitchen
        - conditions:
            - condition: trigger
              id: "homeheating"
          sequence:
            - service: climate.set_preset_mode
              data:
                preset_mode: 'home'
              target:
                entity_id:
                  - climate.upstairs
                  - climate.downstairs
                  - climate.office
                  - climate.kitchen
            - service: climate.set_hvac_mode
              data:
                hvac_mode: 'heat'
              target:
                entity_id:
                  - climate.upstairs
                  - climate.downstairs
                  - climate.office
                  - climate.kitchen
      default: []
  mode: single

- id: '902'
  alias: Heating >> Morning
  description: '30 min befor the morning alarm goes off the heating will come on '
  mode: single
  trigger:
    - platform: template
      value_template: >-
        {{now().strftime('%a %h %d %H:%M %Z %Y') ==
                (((state_attr('sensor.rich_s21_next_alarm', 'Time in Milliseconds') |
                int / 1000) - 30*60 ) | timestamp_custom('%a %h %d %H:%M %Z %Y')) }}
    - platform: template
      value_template: >-
        {{now().strftime('%a %h %d %H:%M %Z %Y') ==
                (((state_attr('sensor.faye_s10e_next_alarm', 'Time in Milliseconds') |
                int / 1000) - 30*60 ) | timestamp_custom('%a %h %d %H:%M %Z %Y')) }}
  condition:
    - condition: time
      after: '04:30'
      before: '09:00'
    - condition: state
      entity_id: group.persons
      state: 'home'
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: binary_sensor.workday_sensor
              state: "on"
          sequence:
            - service: climate.set_preset_mode
              data:
                preset_mode: 'comfort'
              target:
                entity_id:
                  - climate.upstairs
                  - climate.downstairs
                  - climate.office
            - service: climate.set_hvac_mode
              data:
                hvac_mode: 'heat'
              target:
                entity_id:
                  - climate.upstairs
                  - climate.downstairs
                  - climate.office
    - choose:
        - conditions:
            - condition: state
              entity_id: binary_sensor.workday_sensor
              state: "off"
          sequence:
            - service: climate.set_preset_mode
              data:
                preset_mode: 'comfort'
              target:
                entity_id:
                  - climate.upstairs
                  - climate.downstairs
            - service: climate.set_hvac_mode
              data:
                hvac_mode: 'heat'
              target:
                entity_id:
                  - climate.upstairs
                  - climate.downstairs
    - choose:
        - conditions:
            - condition: state
              entity_id: switch.hotwater
              state: 'on'
            - condition: state
              entity_id: switch.boiler_call
              state: 'off'
          sequence:
            - service: homeassistant.turn_off
              target:
                entity_id:
                  - switch.boiler_call


- id: '903'
  alias: Heating >> Night
  trigger:
    - platform: state
      entity_id: input_boolean.night_mode
      to: 'on'
  condition:
    - condition: state
      entity_id: group.persons
      state: 'home'
  action:
    - service: climate.set_preset_mode
      data:
        preset_mode: 'sleep'
      target:
        entity_id:
          - climate.upstairs
          - climate.downstairs
          - climate.office
    - service: climate.set_hvac_mode
      data:
        hvac_mode: 'heat'
      target:
        entity_id:
          - climate.upstairs
          - climate.downstairs
          - climate.office

- id: '905' 
  alias: 'Heating >> HA reboot'
  trigger:
    - platform: homeassistant
      event: start
  action:
    - condition: or
      alias: "HA rebooted and heating was previously needed"
      conditions:
        - condition: state 
          entity_id: switch.downstairs_radiators
          state: "on"
        - condition: state
          entity_id: switch.upstairs_radiators
          state: "on"
        - condition: state
          entity_id: switch.underfloor_heating
          state: "on"
        - condition: state
          entity_id: switch.hotwater
          state: "on"
    - service: homeassistant.turn_on
      target:
        entity_id:
          - switch.boiler_call
    - condition: state
      entity_id: group.persons
      state: "home"
    - service: climate.set_hvac_mode
      data:
        hvac_mode: 'heat'
      target:
        entity_id:
          - climate.upstairs
          - climate.downstairs
          - climate.kitchen


