- name: porch_rstp
  host: !secret Camip1
  username: !secret cctvusername
  password: !secret cctvpassword
  
- name: garden_rstp
  host: !secret Camip2
  username: !secret cctvusername
  password: !secret cctvpassword

- name: driveway_rstp  
  host: !secret Camip3
  username: !secret cctvusername
  password: !secret cctvpassword
