- name: porch_rstp
  host: 192.168.110.241
  username: admin
  password: Farmer79!!
  
- name: garden_rstp
  host: 192.168.110.242
  username: admin
  password: Farmer79!!
  
- name: driveway_rstp  
  host: 192.168.110.243
  username: admin
  password: Farmer79!!
