- platform: template
  sensors:
    downst_bath_fan:
      value_template: >-
        {% set humid = states('sensor.broom_d_th_e160_humidity')|int(default=0) %}
        {% set avg = states('sensor.downstairs_bathroom_humidity_average_linear_24h')|int(default=0) %}
        {% set thresh = 5 %}
        {{ (humid - avg) > thresh }}

- platform: template
  sensors:
    upstairs_bath_fan:
      value_template: >-
        {% set humid = states('sensor.m_broom_th_4aeb_humidity')|int(default=0) %}
        {% set avg = states('sensor.upstairs_bathroom_humidity_average_linear_24h')|int(default=0) %}
        {% set thresh = 5 %}
        {{ (humid - avg) > thresh }}


- platform: template
  sensors:
    heating_crtl:
      value_template: >-
        {{is_state('binary_sensor.heating_controls', 'off')
            or is_state('binary_sensor.underfloor_heating', 'off')
            or is_state('binary_sensor.heating_controls', 'off') }}
            

  