homeassistant: !include homeassistant.yaml

logger:
  default: info
  logs:
    homeassistant.helpers.template: error

default_config:


http: !include http.yaml

recorder:
  purge_keep_days: 7
  db_url: !secret mysql 

ffmpeg:

mobile_app:

#lovelace:
#  mode: yaml
#  resources:
#    - url: /hacsfiles/simple-thermostat/simple-thermostat.js
#      type: module
#    - url: /local/lovelace-swipe-navigation/swipe-navigation.js?v=1.0.0
#      type: module
#    - url: /hacsfiles/frigate-hass-card/frigate-hass-card.js
#      type: module




automation: !include automations.yaml
#script: !include scripts.yaml
scene: !include scenes.yaml
#input_boolean: !include input_boolean.yaml
climate: !include climate.yaml
notify: !include notify.yaml
alert: !include alerts.yaml
#template: !include template.yaml
sensor: !include sensor.yaml
#binary_sensor: ! binary_sensor.yaml