# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

recorder:
  purge_keep_days: 7
  db_url: !secret mysql

ffmpeg:

logger:
  default: warning

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.0.1.0/24

# planning to use a mobile application that integrates with Home Assistant
mobile_app:

lovelace:
  mode: yaml
  resources:
    - url: /local/simple-thermostat.js
      type: module
    - url: /local/lovelace-swipe-navigation/swipe-navigation.js?v=1.0.0
      type: module
    - url: /local/frigate-hass-card.js
      type: module

# Text to speech
tts:
  - platform: google_translate
    cache: true
    time_memory: 300
    cache_dir: /tmp/tts
    base_url: !secret url
    service_name: google_say

group: !include groups.yaml
automation: !include_dir_merge_list automation
script: !include scripts.yaml
scene: !include scenes.yaml
input_boolean: !include input_boolean.yaml
climate: !include climate.yaml
cloud: !include cloud.yaml
notify: !include notify.yaml
alert: !include alerts.yaml
template: !include template.yaml
sensor: !include sensor.yaml
light: !include lights.yaml
binary_sensor: !include  binary_sensor.yaml
amcrest: !include amcrest.yaml