homeassistant: !include homeassistant.yaml

logger:
  default: info
  logs:
    homeassistant.helpers.template: error

default_config:


http: !include http.yaml

recorder:
  purge_keep_days: 7
  db_url: !secret mysql 

ffmpeg:

mobile_app:

automation: !include automations.yaml
climate: !include climate.yaml
notify: !include notify.yaml
alert: !include alerts.yaml
template: !include template.yaml
sensor: !include sensor.yaml
scene: !include scenes.yaml