
coop_cleanning:
  name: Coop cleaning
  initial: off

guest_room:
  name: Enable guest room
  initial: off

eating_mode:
  name: Eating
  initial: off

night_mode:
  name: Night mode
  initial: off
  icon: mdi:sleep

richinbed:
  name: Rich is in bed
  initial: off
  icon: mdi:sleep

fayeinbed:
  name: Faye is in bed
  initial: off
  icon: mdi:sleep
