- platform: group
  name: garden lights
  entities:
    - light.kitchen_outside_lights
    - light.driveway_light

- platform: group
  name: lounge bookshelf lights
  view: no
  entities:
    - light.bookshelf_light_left
    - light.bookshelf_light_right
    