- platform: group
  name: garden lights
  entities:
    - light.kitchen_outside_lights
    - light.driveway_light

- platform: group
  name: lounge bookshelf lights
  entities:
    - light.bookshelf_light_left
    - light.bookshelf_light_right

- platform: group
  name: lounge side lights
  entities:
    - light.bookshelf_light_right
    - light.bookshelf_light_left
    - light.lounge_lamp

#