- platform: group
  name: garden lights
  entities:
    - light.kitchen_outside_lights
    - light.driveway_light

- platform: group
  name: lounge bookshelf lights
  entities:
    - light.lounge_bookshelf_llight
    - light.lounge_bookshelf_rlight
