  - platform: group
    name: notify.all
    services:
      - service: mobile_app_rich_s21
      - service: mobile_app_richards_macbook_pro_home
      - service: mobile_app_richards_macbook_pro
      - service: mobile_app_faye_s10e


  - platform: group
    name: notification gate left open
    services:
      - service: mobile_app_rich_phone
        data:
          message: >
            The Garden gate has been left open!
          data:
            ttl: 0
            priority: high
            channel: alarm_stream_max
            actions:
              - action: "back_gate_alarm"
                title: "Cancel alarm"
