- name: Lounge evening lights
  entities:
    light.lounge_bookshelf_llight:
      state: 'on'
    light.lounge_bookshelf_rlight:
      state: 'on'
    light.lounge:
      state: 'off'
    light.shellyvintage_6edcb8:
      state: 'on'

- name: appliances_on
  entities:
    switch.dishwasher:
      state: 'on'
    switch.washing_machine:
      state: 'on'
    switch.tumble_dryer:
      state: 'on'



- name: nightmode
  entities:
    switch.dishwasher:
      state: 'off'
    switch.washing_machine:
      state: 'off'
    switch.tumble_dryer:
      state: 'off'
    switch.office_door_lock:
      state: 'off'
    switch.playroom_fairy_lights:
      state: 'off'

- name: evening lights
  entities:
    switch.playroom_fairy_lights:
      state: 'on'
    light.lounge_side_lights:
      state: 'on'
    light.fairy_lights:
      state: 'on'
    light.boiler_lamp:
      state: 'on'

- name: morning nolights
  entities:
    light.lounge_bookshelf_llight:
      state: 'off'
    light.lounge_bookshelf_rlight:
      state: 'off'
    light.globe_lamp:
      state: 'off'
    light.kitchen_fairy:
      state: 'off'
    light.kitchen_side:
      state: 'off'
    light.boiler_lamp:
      state: 'off'
    light.kitchen_island_lights:
      state: 'off'
    switch.lila_s_multi_psu_socket_1:
      state: 'off'
    switch.thea_s_multi_psu_socket_1:
      state: 'off'
    light.bathroom_mirror:
      state: 'off'
    light.shellyvintage_6edcb8:
      state: 'off'

- name: morning lights
  entities:
    light.lounge_bookshelf_llight:
      state: 'on'
    light.lounge_bookshelf_rlight:
      state: 'on'
    light.globe_lamp:
      state: 'on'
    light.kitchen_fairy:
      state: 'on'
    light.kitchen_side:
      state: 'on'
    light.boiler_lamp:
      state: 'on'
    light.kitchen_island_lights:
      state: 'on'
    switch.lila_s_multi_psu_socket_1:
      state: 'on'
    switch.thea_s_multi_psu_socket_1:
      state: 'on'
    light.shellyvintage_6edcb8:
      state: 'on'

- name: Kitchen_morning_lowlights
  entities:
    light.kitchen_side:
      state: 'on'
    light.boiler_lamp:
      state: 'on'
    light.kitchen_fairy:
      state: 'on'



#