
- platform: min_max
  entity_ids:
    - sensor.porch_temperature
    - sensor.driveway_temperature
  type: mean
  name: Outside temperature

- platform: min_max
  entity_ids:
    - sensor.landing_temperature
    - sensor.lila_room_temperature
    - sensor.master_room_temperature
    - sensor.thea_room_temperature
  type: mean
  name: Upstairs temperature

- platform: min_max
  entity_ids:
    - sensor.lounge_temperature
    - sensor.playroom_temperature
    - sensor.downstairs_toilet_temperature
    - sensor.hallway_temperature
  type: mean
  name: Downstairs temperature

- platform: time_date
  display_options:
    - 'time'
    - 'date'
