
- platform: statistics
  name: Downstairs Bathroom Humidity Average Linear 24h
  entity_id: sensor.broom_d_th_e160_humidity
  state_characteristic: average_linear
  max_age:
    hours: 24

- platform: statistics
  name: Upstairs Bathroom Humidity Average Linear 24h
  entity_id: sensor.m_broom_th_4aeb_humidity
  state_characteristic: average_linear
  max_age:
    hours: 24
