- binary_sensor:
  
    - name: "No activity downstairs"
      state: >
        {{ is_state('binary_sensor.hallway_pir' , 'off')
            and is_state('binary_sensor.kitchen_pir' , 'off')
            and is_state('binary_sensor.espresense_lounge_motion' , 'off') }}

    - name: "No activity upstairs"
      state: >
        {{ is_state('binary_sensor.landing_pir' , 'off')
            and is_state('binary_sensor.lila_s_pir' , 'off')
            and is_state('binary_sensor.espresense_masterbedroom_motion' , 'off')
            and is_state('binary_sensor.thea_s_bedroom_pir' , 'off') }}

    - name: All pirs
      state: >
        {{ is_state('binary_sensor.landing_pir' , 'off')
            and is_state('binary_sensor.hallway_pir' , 'off')
            and is_state('binary_sensor.lila_s_pir' , 'off')
            and is_state('binary_sensor.espresense_masterbedroom_motion' , 'off')
            and is_state('binary_sensor.kitchen_pir' , 'off')
            and is_state('binary_sensor.espresense_lounge_motion' , 'off')
            and is_state ('binary_sensor.espresense_playroom_motion' , 'off')
            and is_state('binary_sensor.thea_s_bedroom_pir' , 'off') }}
    
    - name: Enable auto lights
      delay_off:
        minutes: 5
      state: >
        {{ states('sensor.out_side_lux')|float < 1400 }}