- binary_sensor:
      - name: "Pressure 1 or 2 High"
        state: >
          {{ states('sensor.pressure_1')|float > 1.00
            or states('sensor.pressure_2')|float > 1.00 }}
        delay_on: "00:05:00"
