- binary_sensor:  
    - name: "No activity downstairs"
      state: >
        {{ is_state('binary_sensor.hallway_pir' , 'off')
            and is_state('binary_sensor.kitchen_pir' , 'off')
            and is_state('binary_sensor.lounge_pir' , 'off') }}
  
    - name: "noheating"
      state: >      
        {% if is_state('switch.downstairs_radiators', 'off')
            and is_state('switch.upstairs_radiators', 'off')
            and is_state('switch.hotwater', 'off') %}
            on
        {% else %}
          off
        {% endif %}
  
    - name: "No activity upstairs"
      state: >
        {{ is_state('binary_sensor.landing_pir' , 'off')
            and is_state('binary_sensor.lila_bedroom_pir' , 'off')
            and is_state('binary_sensor.master_bedroom_pir' , 'off')
            and is_state('binary_sensor.thea_s_bedroom_pir' , 'off') }}

    - name: All pirs
      state: >
        {{ is_state('binary_sensor.landing_pir' , 'off')
            and is_state('binary_sensor.hallway_pir' , 'off')
            and is_state('binary_sensor.lila_bedroom_pir' , 'off')
            and is_state('binary_sensor.master_bedroom_pir' , 'off')
            and is_state('binary_sensor.kitchen_pir' , 'off')
            and is_state('binary_sensor.lounge_pir' , 'off')
            and is_state ('binary_sensor.playroon_pir' , 'off')
            and is_state('binary_sensor.thea_s_bedroom_pir' , 'off') }}
    
    - name: Enable auto lights
      delay_off:
        minutes: 5
      state: >
        {{ states('sensor.out_side_lux')|float < 1200 }}
    
    - name: Enable auto outside lights
      delay_off:
        minutes: 5
      state: >
        {{ states('sensor.out_side_lux')|float < 200 }}


#