title: Edenbridge
swipe_nav:
  wrap: true
  swipe_amount: 30
  animate: swipe

views:
  - title: main
    path: main
    icon: mdi:information-outline
    cards:
      - type: entities
        title: Who´s at Home
        entities:
          - person.faye_dawson
          - person.richard_dawson
      
      - type: weather-forecast
        entity: weather.openweathermap
      
      - type: sensor
        entity: sensor.out_side_lux
        name: Outside Lux
      
      - type: button
        entity: input_boolean.night_mode
        show_name: false
        show_state: false
        show_icon: true

  - title: CCTV
    icon: mdi:camera
    path: cctv
    cameras:
      - camera_entity: camera.backgarden
    live_provider: ha
    engine: auto
    hide: false
    frigate:
      url: http://192.168.111.23:30005
      client_id: frigate
      camera_name: backgarden
      labels:
        - person
    triggers:
      motion: false
      occupancy: true
      entities:
        - binary_sensor.kitchen_door
    
    

  - title: Heating
    icon: mdi:radiator
    path: heating
    cards:
      - type: 'custom:simple-thermostat'
        entity: climate.downstairs
        step_size: 1
        sensors:
          - entity: sensor.playroom_s_room_humidity
            name: Humidity
      - type: 'custom:simple-thermostat'
        entity: climate.upstairs
        step_size: 1
        sensors:
          - entity: sensor.playroom_s_room_humidity
            name: Humidity
      - type: 'custom:simple-thermostat'
        entity: climate.kitchen
        step_size: 1
        sensors:
          - entity: sensor.kitchen_humidity
            name: Humidity
      - type: 'custom:simple-thermostat'
        entity: climate.office
        step_size: 1
        sensors:
          - entity: sensor.office_humidity
            name: Humidity



  - title: Rooms
    path: rooms
    icon: mdi:home-outline

    cards:
      - type: glance
        title: Master bedroom
        entities:
          - entity: light.master_bedroom_light
          - entity: binary_sensor.master_bedroom_pir
          - entity: sensor.m_room_th_d068_temperature
          - entity: sensor.m_room_th_d068_humidity


      - type: glance
        title: Lila´s bedroom
        entities:
          - entity: light.lila_s_bedroom_light
          - entity: binary_sensor.lila_bedroom_pir
          - entity: sensor.lila_th_968e_temperature

      - type: glance
        title: Thea´s bedroom
        entities:
          - entity: light.thea_s_bedroom_light
          - entity: binary_sensor.thea_s_bedroom_pir
          - entity: sensor.thea_th_b94c_temperature
          - entity: light.thea_s_mirror_lights

      - type: glance
        title: Playroom
        entities:
          - entity: light.playroom_light_s
          - entity: binary_sensor.playroom_pir
          - entity: sensor.playrom_th_c5d5_temperature
          - entity: light.playroom_fairy_lights
      - type: glance
        title: Lounge
        entities:
          - entity: light.lounge_bookshelf_lights
          - entity: light.lounge_main_light
          - entity: binary_sensor.lounge_pir
          - entity: light.lounge_lamp
          - entity: sensor.lounge_th_4ab5_temperature
          - entity: light.lounge_side_lights

      - type: glance
        title: Kitchen
        entities:
          - entity: light.kitchen_dining
          - entity: light.side_lights
          - entity: light.kitchen_island
          - entity: light.fairy_lights
          - entity: binary_sensor.kitchen_pir
          - entity: light.boiler_lamp
          - entity: sensor.kitchen_th_819f_temperature
          - entity: sensor.underfloor_heating_temperature
          - entity: switch.dishwasher
          - entity: switch.washing_machine
          - entity: switch.tumble_dryer
          - entity: binary_sensor.kitchen_door


      - type: glance
        title: Landing / Hallway
        entities:
          - entity: light.landing_lights
          - entity: light.hallway_light_s
          - entity: sensor.landing_th_b54e_temperature
          - entity: sensor.hallway_th_e88a_temperature
          - entity: binary_sensor.hallway_pir
          - entity: binary_sensor.landing_pir


      - type: glance
        title: Office
        entities:
          - entity: switch.office_door_lock
          - entity: light.office_loft_light
          - entity: sensor.office_th_c4d6_temperature
          - entity: sensor.office_th_c4d6_humidity
          - entity: binary_sensor.office_door
          - entity: light.office_light_s


      - type: glance
        title: Back garden
        entities:
          #- entity: binary_sensor.garden_gate
          - entity: light.garden_lights
          - entity: sensor.driveway_temperature

      - type: glance
        title: Front garden
        entities:
          - entity: light.porch_light
          - entity: binary_sensor.front_door
          - entity: sensor.porch_temperature

      - type: glance
        title: Bathroom
        entities:
          - entity: light.bathroom_mirror_light
          - entity: light.bathroom_light
          - entity: switch.bathroom_extractor_fan
          - entity: sensor.m_broom_th_4aeb_temperature
          - entity: sensor.m_broom_th_4aeb_humidity

      - type: glance
        title: Downstairs toilet
        entities:
          - entity: switch.downstairs_toilet_extractor_fan
          - entity: sensor.broom_d_th_e160_humidity
          - entity: sensor.broom_d_th_e160_temperature

  - title: Master's Switch's
    icon: mdi:toggle-switch
    path: switchs
    cards:
      - type: glance
        entities:
          - entity: input_boolean.coop_cleanning
          - entity: input_boolean.guest_room
          - entity: input_boolean.eating_mode

  - title: Media
    path: Media
    icon: mdi:music
    cards:
      - type: glance
        title: TV players
        entities:
          - entity: media_player.playroom_tv

      - type: glance
        title: Echo's
        entities:
          - entity: media_player.playroom
          - entity: media_player.master_bedroom
          - entity: media_player.thea_bedroom
          - entity: media_player.lila_bedroom
          - entity: media_player.kitchen_2
          - entity: media_player.office
          

      - type: glance
        title: Sonos
        entities:
          - entity: media_player.lounge
          - entity: media_player.kitchen
          - entity: media_player.garden
          - entity: media_player.richard_s_sonos_one


  - title: Chickhen´s
    path: chickhens
    icon: mdi:bird
    cards:
      - type: glance
        entities:
          - entity: switch.coop_door_close
          - entity: switch.coop_door_open
          - entity: binary_sensor.chickens_coop_door
          - entity: binary_sensor.chickens_garden_door

  - title: Controls
    path: Controls
    cards:
      - type: glance
        title: Heating Control´s
        entities:
          - switch.downstairs_radiators
          - switch.upstairs_radiators
          - binary_sensor.cylinder_thermostats
          - switch.underfloor_heating
          - switch.office_heater
          - switch.hotwater
          - switch.boiler_call

