- alias: Android Set Datetime
  trigger:
    platform: state
    entity_id: sensor.sm_g973f_next_alarm
  mode: restart
  condition:
    - condition: not
      conditions:
        - condition: state
          entity_id: sensor.sm_g973f_next_alarm
          state:
            - unavailable
            - unknown
  action:
    - delay: 00:00:30
    - service: input_datetime.set_datetime
      entity_id: input_datetime.rd_android_alarm
      data_template:
        datetime: "{{ as_timestamp(states('sensor.sm_g973f_next_alarm'))|timestamp_custom('%Y-%m-%d %H:%M:00') }}"


- alias: test alarm
  trigger:
    platform: time
    at: input_datetime.rd_android_alarm
  action:
    service: light.turn_on
    entity_id: light.globe_lamp

- alias: Notification Time for School
  initial_state: on
  trigger:
    platform: time
    at: '07:30:00'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: notify.alexa_media
      data:
        target: 
          - media_player.thea_bedroom
          - media_player.lila_bedroom
        #title: "My title for Echo show"
        data:
          type: tts
          #method: all
        message: "Good moring, it time to get up for school"
    - delay: 0:20
    - service: media_player.play_media
      data:
        target: 
          - media_player.thea_bedroom
          - media_player.lila_bedroom
