- alias: No one home check camera´s
  trigger:
    platform: state 
    entity_id:
      - binary_sensor.garden_gate
      - binary_sensor.backgarden_movement
      - binary_sensor.driveway_movement
      - binary_sensor.porch_movement
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: group.persons
        state:  not_home
      - condition: state
        entity_id: input_select.house_mode
        state:  Night
  action:
    - service: notify.mobile_app_sm_g973f
      data:
        message: >
          {{ trigger.payload }}
      
