- alias: Evening motion master bathroom
  trigger:
  - platform: state
    entity_id: binary_sensor.bathroom_switch
    to: 'on'
  condition: 
    condition: and
    conditions:
      - condition: state
        entity_id: light.bathroom
        state: 'off'  
      - condition: state
        entity_id: input_select.house_mode
        state: Evening
  action:
  - service: homeassistant.turn_on
    entity_id: light.bathroom


- alias: Night motion master bathroom
  trigger:
  - platform: state
    entity_id: binary_sensor.bathroom_switch
    to: 'on'
  condition: 
    condition: and
    conditions:
      - condition: state
        entity_id: light.bathroom_mirror
        state: 'off'  
      - condition: state
        entity_id: input_select.house_mode
        state: Night
  action:
  - service: homeassistant.turn_on
    entity_id: light.bathroom_mirror

- alias: No motion master bathroom
  trigger:
  - platform: state
    entity_id: binary_sensor.bathroom_switch
    to: 'off'
    for:
      minutes: 5
  condition:
    condition: or
    conditions: 
      - condition: state
        entity_id: light.bathroom
        state: 'on'
      - condition: state
        entity_id: light.bathroom_mirror
        state: 'on'
  action:
  - service: homeassistant.turn_off
    entity_id: 
      - light.bathroom
  - service: homeassistant.turn_off
    entity_id: 
      - light.bathroom_mirror
