###################################################
## Open and Closing chickehn coop door to garden ## 
###################################################


- alias: Morning open chicken´s coop door
  trigger:
  - platform: numeric_state
    entity_id: sensor.out_side_lux
    above: 300
  action:
  - service: homeassistant.turn_on
    entity_id: switch.coop_door_open
    


- alias: Night time for chicken´s close coop door
  trigger:
  - platform: numeric_state
    entity_id: sensor.out_side_lux
    below: 200
  action:
  - service: homeassistant.turn_on
    entity_id: switch.coop_door_close

- alias: Feed the chickhens 
  trigger:
  - platform: time
    at: "10:20:00"
  condition:
  - condition: state
    entity_id: binary_sensor.chickens_coop_door
    for:
      hours: 1
    state: 'off'
  action:
    - service: notify.mobile_app_sm_g973f
      data:
        message: "No one has Checked on the Chickhen food & water!"
        data:
          actions:
            - action: "alarm" # The key you are sending for the event
              title: "Title" # The button title
            - action: "URI" # Must be set to URI if you plan to use a URI
              title: "Open Url"
              uri: "https://google.com" # URL to open when action is selected, can also be a lovelace view/dashboard
            - action: "URI" # Must be set to URI if you plan to open an application
              title: "Open Twitter"
              uri: "app://com.twitter.android" # Name of package for application you would like to open