- alias: Outside christmas lights on
  trigger:
  - platform: state
    entity_id: input_select.house_mode
    to: 'Evening'
  action:
  - service: homeassistant.turn_on
    entity_id: group.christmas_lights_psu


- alias: Outside christmas lights off
  trigger:
  - platform: state
    entity_id: input_select.house_mode
    to: 'Night'
  action:
  - service: homeassistant.turn_off
    entity_id: group.christmas_lights_psu

