- alias: Outside christmas lights on
  trigger:
  - platform: state
    entity_id: input_select.house_mode
    to: 'Evening'
  action:
  - service: homeassistant.turn_on
    entity_id: group.christmas_lights_psu
  - delay: 00:00:30
  - service: homeassistant.turn_on
    data:
      entity_id: light.front_christmas_lights
      effect_list: Merry Christmas


- alias: Outside christmas lights off
  trigger:
  - platform: state
    entity_id: input_select.house_mode
    to: 'Night'
  action:
  - service: homeassistant.turn_off
    entity_id: group.christmas_lights_psu

