- alias: Heating On
  trigger:
    - platform: template
      value_template: >
        {{ is_state('switch.downstairs_radiators', 'on') or
          is_state('switch.upstairs_radiators', 'on') or
          is_state('switch.underfloor_heating', 'on') }}
  condition:
    condition: not
    conditions:
      - condition: state
        entity_id: switch.boiler_call
        state: 'on'
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.boiler_call



- alias: Hotwater on
  trigger:
    - platform: state
      entity_id: switch.hotwater
      to: 'on'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: switch.boiler_call
          state: 'off'
        - condition: or
          conditions: 
            - condition: state
              entity_id: input_select.house_mode
              state: 'Day+lights'
            - condition: state
              entity_id: input_select.house_mode
              state: 'Day'
            - condition: or
              conditions:
                - condition: state
                  entity_id: person.richard
                  state: 'home'
                - condition: state
                  entity_id: person.faye
                  state: 'home'
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.boiler_call


- alias: Heating Off
  trigger:
    - platform: template
      value_template: >
        {{ is_state('switch.downstairs_radiators', 'off') and
          is_state('switch.underfloor_heating', 'off') and
          is_state('switch.upstairs_radiators', 'off') and
          is_state('switch.hotwater', 'off') }}
  condition:
    condition: not
    conditions:
      - condition: state
        entity_id: switch.boiler_call
        state: 'off'
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.boiler_call 
  
  
- alias: HA restart hotwater
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: input_select.house_mode
      to: "Day"
    - platform: state
      entity_id: input_select.house_mode
      to: "Day+lights"
  condition: 
    - condition: state
      entity_id: switch.hotwater
      state:   "on"
    - condition: state
      entity_id: switch.boiler_call
      state: "off"
  action:
    - service: switch.turn_on
      target:
        entity_id: switch.boiler_call


- alias: Day mode Heating
  trigger:
    - platform: state
      entity_id: input_select.house_mode
      to:  Day
  action:
    - service: climate.set_temperature 
      target:
        entity_id: climate.upstairs
      data:
        temperature: 18
        hvac_mode: heat

- alias: Night mode Heating
  trigger:
    - platform: state
      entity_id: input_select.house_mode
      to:  Night
  action:
    - service: climate.set_temperature 
      target:
        entity_id: climate.upstairs
      data:
        temperature: 18
        hvac_mode: heat
    - service: climate.set_temperatue
      target:
        entity_id: climate.downstairs
      data:
        temperature: 18
        hvac_mode: heat
  
- alias: No ones home turn off Heating
  trigger:
    - platform: template
      value_template: >
        {{ is_state('person.faye', 'not_home') and
          is_state('person.richard', 'not_home') }}
      for:
        minutes: 20
  action:
    - service: climate.set_preset_mode 
      target:
        entity_id: climate.upstairs
      data:
        preset_mode: away
    - service: climate.set_preset_mode 
      target:
        entity_id: climate.downstairs
      data:
        preset_mode: away

- alias: home Turn on Heating
  trigger:
    - platform: template
      value_template: >
        {{ is_state('person.faye', 'home') or
          is_state('person.richard', 'home') }}
    - platform: homeassistant
      event: start
  condition:
    - condition: or
      conditions: 
        - condition: state
          entity_id: 'person.richard'
          state: 'home' 
        - condition: state
          entity_id: 'person.faye'
          state: 'home' 
  action:
    - service: climate.set_preset_mode 
      target:
        entity_id:
          - climate.kitchen
          - climate.upstairs
          - climate.downstairs
      data:
        preset_mode: none
    - service: climate.set_hvac_mode
      target:
        entity_id:
          - climate.kitchen
          - climate.upstairs
          - climate.downstairs
      data:  
        hvac_mode: heat

