- alias: Heating On
  trigger:
  - platform: template
    value_template: >
      {{ is_state('switch.downstairs_radiators', 'on') or
        is_state('switch.upstairs_radiators', 'on') or
        is_state('switch.underfloor_heating', 'on') }}
  condition:
    condition: not
    conditions:
      - condition: state
        entity_id: switch.boiler_call
        state: 'on'
  action:
  - service: switch.turn_on
    entity_id: switch.boiler_call

