- alias: Heating On
  trigger:
    - platform: template
      value_template: >
        {{ is_state('switch.downstairs_radiators', 'on') or
          is_state('switch.upstairs_radiators', 'on') or
          is_state('switch.underfloor_heating', 'on') or
          is_state('switch.hotwater', 'on') }}
  action:
    - service: switch.turn_on
      entity_id: switch.boiler_call

- alias: Heating Off
  trigger:
    - platform: template
      value_template: >
        {{ is_state('switch.downstairs_radiators', 'off') and
          is_state('switch.underfloor_heating', 'off') and
          is_state('switch.upstairs_radiators', 'off') and
          is_state('switch.hotwater', 'off') }}
  action:
    - service: switch.turn_off
      entity_id: switch.boiler_call
      
      
- alias: Heating control are on and working 
  trigger:
    - platform: template
      value_template: >
        {{ is_state('binary_sensor.heating_controls_node_05' , 'on') and
          is_state('binary_sensor.heating_controls_node_02' , 'on') and
          is_state('binary_sensor.boiler_node_03' , 'on') }}
  action:
    - service: homeassistant.turn_on
      entity_id: automation.heating_on

- alias: Heating control are off time to investagate  
  trigger:
    - platform: template
      value_template: >
        {{ is_state('binary_sensor.heating_controls_node_05' , 'off') or
          is_state('binary_sensor.heating_controls_node_02' , 'off') or
          is_state('binary_sensor.boiler_node_03' , 'off') }}
  action:
    - service: homeassistant.turn_off
      entity_id: 
        - automation.heating_on
        - switch.boiler_call
    - delay: 2:00    
    - service: notify.mobile_app_sm_g973f
      data_template:
        message: >
          {% if is_state('binary_sensor.heating_controls_node_05' , 'off') or
            is_state('binary_sensor.underfloor_heating_node_02' , 'off' ) or
            is_state('binary_sensor.boiler_node_03' , 'off') %}
            Heating Control has been disabled, please investage!
          {% else %}
            Heating Control´s are back on and working!
          {% endif %}

- alias: Morning Heating 
  trigger:
    value_template: "{{ states('sensor.time') == ( states.input_datetime.rd_android_alarm.attributes.timestamp | int - 1800 ) | timestamp_custom('%H:%M', False) }}"
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.upstairs
        temperature: 21.5
        hvac_mode: heat
