
- alias: Morning
  trigger:
    - platform: state
      entity_id: sensor.ds_pirs
      to: 'False'
  condition:
    - condition: state
      entity_id: sensor.us_pirs
      state: 'True'
      for:
        minutes: 5 
    - condition: sun
      after: sunrise
      before: sunset
      before_offset: "-06:00:00"
  action:
    - service: input_select.set_options
      data:
        entity_id: input_select.house_mode
        options: Morning


- alias: Evening mode
  trigger:
    - platform: numeric_state
      entity_id: sensor.out_side_lux
      below: 5000
  condition:
    condition: sun
    after: sunrise
    after_offset: "+06:00:00"
    before: sunset
  action:
    - service: input_select.set_options
      data:
        entity_id: input_select.house_mode
        options: Evening


- alias: Night mode
  trigger:
    - platform: state
      entity_id: sensor.us_pirs
      to: 'True'
      for:
        minutes: 20
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.ds_pirs
        state: 'True'
        for:
          minutes: 15
      - condition: numeric_state
        entity_id: sensor.out_side_lux
        below: 4
      - condition: or
        conditions:
        - condition: sun
          after: sunset
        - condition: sun
          before: sunrise
  action:
    - service: input_select.set_options
      data:
        entity_id: input_select.house_mode
        options: Night

- alias: Set Scene House Mode
  trigger:
    - platform: state
      entity_id: input_select.house_mode
  action:
    - service: scene.turn_on
      data_template:
        entity_id: >
          {%- if is_state('input_select.house_mode' , 'Morning') %}
            scene.morning
          {% elif is_state('input_select.house_mode' , 'Evening') %}
            scene.evening_lights
          {% elif is_state('input_select.house_mode' , 'Night') %}  
            scene.nightmode
          {% endif %}

