

- alias: Evening without lights
  trigger:
    - platform: state
      entity_id: binary_sensor.lights
      from: 'off'
      to: 'on'
  condition:
    - condition: template
      value_template: "{{ (state_attr('sun.sun','rising') == false) }}"
    - condition: template
      value_template: "{{ state_attr('sun.sun', 'elevation') < 6 }}"
    - condition: not
      conditions:
        - condition: state
          entity_id: input_select.house_mode
          state: "Night"
  action:
    - service: scene.turn_on
      data: {}
      target:
        entity_id: scene.evening_lights
      


- alias: Night mode
  trigger:
    - platform: state
      entity_id: sensor.us_pirs
      to: 'True'
      for:
        minutes: 20
  condition:
    - condition: state
      entity_id: sensor.ds_pirs
      state: 'True'
      for:
        minutes: 15
    - condition: template
      value_template: "{{ (state_attr('sun.sun','rising') == false) }}"
    - condition: template
      value_template: "{{ state_attr('sun.sun', 'elevation') < -18 }}"
    - condition: state
      entity_id: binary_sensor.lounge_tv_status
      state: 'off'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.house_mode
        option: "Night"

- alias: Gone out switch lights and power off
  trigger:
    - platform: state
      entity_id: sensor.all_pirs
      to: 'true'
      for: '00:20:00'
  condition:
    condition: not
    conditions:
      - condition: state
        entity_id: group.persons
        state: 'home'
  action:
    - service: light.turn_off
      entity_id: all
    - service: homeassistant.turn_off
      entity_id: switch.dishwasher_switch

- alias: Out hours movment
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.porch_movement
        - binary_sensor.backgarden_movement
        - binary_sensor.coop_movement
        - binary_sensor.driveway_movement
        - binary_sensor.sidedrive_movement
      to: 'on'
  condition:
    - condition: state
      entity_id: input_select.house_mode
      state: Night
  action:
    - service: notify.mobile_app_rich_phone
      data:
        message: >
          Night mode enabled: At {{states('sensor.time')}} movement on {{trigger.to_state.name}} camera!

- alias: Someone has entered house perimeter (no one is home)
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.porch_movement
        - binary_sensor.backgarden_movement
        - binary_sensor.driveway_movement
      to: 'on'
  condition:
    condition: not
    conditions:
      - condition: state
        entity_id: group.persons
        state: 'home'
  action:
    - service: notify.mobile_app_rich_phone
      data:
        message: >
          Everyone is out: At {{states('sensor.time')}} movement on {{trigger.to_state.name}} camera!

