###############################################################
## Hallway 
################################################################

- alias: Motion Sensor Hallway On
  trigger:
  - platform: state
    entity_id: binary_sensor.hallway_pir
    to: 'on'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_select.house_mode
        state: Evening
      - condition: state
        entity_id: input_select.house_mode
        state: Night
      - condition: state
        entity_id: input_select.house_mode
        state: Morning+lights
  action:
  - service: homeassistant.turn_on
    entity_id: light.hallway_lights
    

- alias: Motion Sensor Hallway Off
  trigger:
  - platform: state
    entity_id: binary_sensor.hallway_pir
    to: 'off'
    for:
      minutes: 5
  action:
  - service: homeassistant.turn_off
    entity_id: light.hallway_lights


###############################################################
## Playroom
###############################################################

- alias: Motion Sensor Playroom On
  trigger:
  - platform: state
    entity_id: binary_sensor.playroom_pir
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: 
          - input_boolean.guest_room
          - light.globe_lamp
        state: 'off'
      - condition: or
        conditions:
          - condition: state
            entity_id: input_select.house_mode
            state: Evening
          - condition: state
            entity_id: input_select.house_mode
            state: Night
          - condition: state
            entity_id: input_select.house_mode
            state: Morning+lights
  action:
  - service: homeassistant.turn_on
    entity_id: light.playrooms_light
    

- alias: Motion Sensor Playroom Off
  trigger:
  - platform: state
    entity_id: binary_sensor.playroom_pir
    to: 'off'
    for:
      minutes: 5
  condition:
  - condition: state      
    entity_id: input_boolean.guest_room
    state: 'off'
  action:
  - service: homeassistant.turn_off
    entity_id: light.playrooms_light


###############################################################
## Landing
###############################################################


- alias: Motion Sensor Landing On
  trigger:
  - platform: state
    entity_id: binary_sensor.landing_pir
    to: 'on'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_select.house_mode
        state: Evening
      - condition: state
        entity_id: input_select.house_mode
        state: Night
      - condition: state
        entity_id: input_select.house_mode
        state: Morning+lights
  action:
  - service: homeassistant.turn_on
    entity_id: light.landing_lights
  

- alias: Motion Sensor Landing Off
  trigger:
  - platform: state
    entity_id: binary_sensor.landing_pir
    to: 'off'
    for:
      minutes: 5
  action:
  - service: homeassistant.turn_off
    entity_id: light.landing_lights

###############################################################
## Lila´s Room
###############################################################  

- alias: Motion Sensor Lila Off
  trigger:
  - platform: state
    entity_id: binary_sensor.lila_s_pir
    to: 'off'
    for:
      minutes: 5
  action:
  - service: homeassistant.turn_off
    entity_id: light.lila_s_bedroom_light

###############################################################
## Thea´s Room
###############################################################
    
- alias: Motion Sensor Thea Off
  trigger:
  - platform: state
    entity_id: binary_sensor.thea_s_bedroom_pir
    to: 'off'
    for:
      minutes: 5
  action:
  - service: homeassistant.turn_off
    entity_id: light.thea_s_bedroom_light



###############################################################
## Master bedroom
###############################################################

- alias: Motion Sensor Thea Off
  trigger:
  - platform: state
    entity_id: binary_sensor.raf_s_pir
    to: 'off'
    for:
      minutes: 5
  action:
    - service: homeassistant.turn_off
      entity_id: 
        - light.master_bedroom_light