- alias: Switch kitchen light off TV on
  trigger:
    - platform: state
      entity_id: binary_sensor.lounge_tv_status
      to:  'on'
  condition:
    - condition: state
      entity_id: input_select.house_mode
      state:  Evening
    - condition: state
      entity_id: binary_sensor.kitchen_pir
      state: 'off'
      for:
        minutes: 5
  action:
    - service: light.turn_off
      entity_id: light.kgl

- alias: Switch playroom tv and player
  trigger:
    - platform: state
      entity_id: binary_sensor.playroom_pir
      to:  'off'
      for:
        minutes: 10
  condition:
    condition: not
    conditions:
      - condition: state
        entity_id: media_player.playroom
        state:  'Playing'
      - condition: state
        entity_id: switch.tv
        state: 'off'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.tv
      
  