- alias: Heating set & house set to morning mode
  trigger:
    - platform: state
      entity_id: binary_sensor.alarm_heating_on
      to: 'on'
    - platform: time
      at: "08:00:00"
  condition:
    - condition: time
      after: '05:00'
      before: '09:00'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: input_select.house_mode
        option: >
          {% if states('sensor.out_side_lux')| float  > 1400 %}
            Awake
          {% else %}
            Awake+lights
          {% endif %}
    - condition: and
      conditions:
        - condition: state
          entity_id: group.persons
          state: "home"
    - service: climate.set_temperature 
      target:
        entity_id: 
          - climate.upstairs
          - climate.downstairs
      data:
        temperature: 20
    - service: climate.set_temperature 
      target:
        entity_id: 
          - climate.office
      data:
        temperature: 17
    - service: climate.set_hvac_mode
      target:
        entity_id: 
          - climate.upstairs
          - climate.downstairs
          - climate.office
      data:
        hvac_mode: heat
    - service: scene.turn_on
      data: {}
      target:
        entity_id: scene.appliances

        






