- alias: Heating set & house set to morning mode
  description: ''
  trigger:
    - platform: state
      entity_id: binary_sensor.alarm_heating_on
      to: 'on'
    - platform: time
      at: "09:00:10"
  condition:
    - condition: time
      after: '05:00'
      before: '09:00'
  action:
    - service: climate.set_temperature 
      target:
        entity_id: 
        - climate.upstairs
        - climate.downstairs
      data:
        temperature: 20
        hvac_mode: heat
    - service: input_select.select_option
      data_template:
        entity_id: input_select.house_mode
        option: >
          {% if states('sensor.out_side_lux')| float  > 2000 %}
            Day
          {% else %}
            Day+lights
          {% endif %}  
  mode: single

- alias: Mode for Day 
  trigger:
    - platform: numeric_state
      entity_id: sensor.out_side_lux
      above: 2001
      below: 2000
  condition:
    - condition: not
      conditions:
        - condition: state
          entity_id:
            - input_select.house_mode
          state: "Night"
  action:
    - service: input_select.select_option
      data_template:
        entity_id: input_select.house_mode
        option: >
          {% if states('sensor.out_side_lux')| float  > 2000 %}
            Day
          {% else %}
            Day+lights
          {% endif %} 

