- alias: Turn on Heating and set house to morning mode
  description: ''
  trigger:
    - platform: state
      entity_id: binary_sensor.alarm_heating_on
      to: 'on'
  condition:
    - condition: time
      after: '05:00'
      before: '09:00'
  action:
    - service: climate.set_temperature 
      target:
        entity_id: climate.upstairs
      data:
        temperature: 20
        hvac_mode: heat
    - service: climate.set_temperature 
      target:
        entity_id: climate.downstairs
      data:
        temperature: 20
        hvac_mode: heat
    - service: input_select.select_option
      data_template:
        entity_id: input_select.house_mode
        option: >
          {% if states('sensor.out_side_lux')| float  > 2000 %}
            Day
          {% else %}
            Day+lights
          {% endif %}  
  mode: single

- alias: Day mode Lights
  trigger:
    - platform: numeric_state
      entity_id: sensor.out_side_lux
      below: 2000
      for:
        minutes: 2
  condition:
    - condition: and
      conditions:
        - condition: time
          after: "09:01"
        - condition: not
          conditions:
            - condition: state
              entity_id:
                - input_select.house_mode
              state: "Night"
  action:
    - service: input_select.select_option
      target:
        entity_id: input_select.house_mode
      data:
        option: "Day+lights"

- alias: Day mode
  trigger:
    - platform: numeric_state
      entity_id: sensor.out_side_lux
      above: 2001 
      for:
        minutes: 2
  condition:
    - condition: and
      conditions:
        - condition: time
          after: "09:01"
        - condition: not
          conditions:
            - condition: state
              entity_id:
                - input_select.house_mode
              state: "Night"
  action:
    - service: input_select.select_option
      target:
        entity_id: input_select.house_mode
      data:
        option: "Day"