- alias: Night mode PIR enabled
  trigger:
    - platform: state
      entity_id: sensor.us_pirs
      to: 'True'
      for:
        minutes: 20
  condition:
    - condition: state
      entity_id: sensor.ds_pirs
      state: 'True'
      for:
        minutes: 15
    - condition: template
      value_template: "{{ (state_attr('sun.sun','rising') == false) }}"
    - condition: template
      value_template: "{{ state_attr('sun.sun', 'elevation') < -18 }}"
    - condition: state
      entity_id: binary_sensor.lounge_tv_status
      state: 'off'
  action:
    - service: scene.turn_on
      data: {}
      target:
        entity_id: scene.nightmode
    - service: input_select.select_option
      data:
        entity_id: input_select.house_mode
        option: "Night"


- alias: Night mode manle 
  trigger:
    - platform: state
      entity_id: input_select.house_mode
      to: 'Night'
  action:
    - service: scene.turn_on
      data: {}
      target:
        entity_id: scene.nightmode


- alias: Out hours movment
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.porch_movement
        - binary_sensor.backgarden_movement
        - binary_sensor.coop_movement
        - binary_sensor.driveway_movement
        - binary_sensor.sidedrive_movement
      to: 'on'
  condition:
    - condition: state
      entity_id: input_select.house_mode
      state: Night
  action:
    - service: notify.mobile_app_rich_phone
      data:
        message: >
          Night mode enabled: At {{states('sensor.time')}} movement on {{trigger.to_state.name}} camera!

- alias: Night mode heating
  trigger:
    - platform: state
      entity_id: input_select.house_mode
      to: 'Night'
  condition:
    - condition: state
      entity_id: group.persons
      state: 'home'
  action:
    - service: climate.set_temperature 
      target:
        entity_id: 
          - climate.upstairs
          - climate.downstairs
      data:
        temperature: 18
