- alias: Backgate or Backdoor opens 
  trigger:
    platform: state
    entity_id: 
      - binary_sensor.kitchen_door
      - binary_sensor.garden_gate
    to: 'on'
  condition: 
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.out_side_lux
        below: 30
      - condition: state
        entity_id: light.garden_lights
        state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: light.garden_lights

- alias: Backgate or Backdoor closed
  trigger:
    platform: state
    entity_id: 
      - binary_sensor.kitchen_door
      - binary_sensor.garden_gate
    to: 'off'
  condition: 
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.out_side_lux
        below: 30
      - condition: state
        entity_id: light.garden_lights
        state: 'on'
  action:
    - delay: 00:05
    - service: homeassistant.turn_off
      entity_id: light.garden_lights







######################################################
## Open front gate or front door for secrity lights ##
######################################################


- alias: frnt gate or frnt door opens 
  trigger:
    platform: state
    entity_id: 
      - binary_sensor.front_door
      - binary_sensor.frontgarden_gate
    to: 'on'
  condition: 
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.out_side_lux
        below: 30
      - condition: state
        entity_id: light.porch_light
        state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: light.porch_light
    - service: timer.start
      entity_id: timer.frntgarden_secritylights

- alias: restart timer frnt garden lights
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.frntgarden_secritylights
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: binary_sensor.front_door
        state: 'on'
      - condition: state
        entity_id: binary_sensor.frontgarden_gate
        state: 'on'
  action:
      - service: timer.start
        entity_id: timer.frntgarden_secritylights


- alias: Switch off frnt garden lights
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.frntgarden_secritylights
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.front_door
        state: 'off'
      - condition: state
        entity_id: binary_sensor.frontgarden_gate
        state: 'off'
  action:
      - service: homeassistant.turn_off
        entity_id: light.porch_light